### Training a Random Forest Regressor model
Training a random forest regressor that predicts FPL points for the upcoming GW for players. This is a general model, and uses position as one of the predictors. A future step might be to produce a separate model for each position so that position-specific features can be better considered.

Rolling game statistics are key to the model - they will be computed on the previous three games for each player, and used as predictor features.

In [1]:
import os
import torch
import pandas as pd
import numpy as np
from model import AdvancedLSTM
import pickle
from eval import get_season_performance, season_performance_with_unlimited_transfers

In [2]:
base_path = os.getcwd()
base_path

'/Users/bragehs/Documents/FPL_forecast/predictor'

In [3]:
data_path = os.path.join(base_path, 'processed_data')
data_path

'/Users/bragehs/Documents/FPL_forecast/predictor/processed_data'

In [4]:
X_train = torch.load(data_path + '/X_train.pt', weights_only=True)
y_train = torch.load(data_path + '/y_train.pt', weights_only=True)
train_mapping = pd.read_csv(data_path + '/train_mapping.csv')

X_val = torch.load(data_path + '/X_val.pt', weights_only=True)
y_val = torch.load(data_path + '/y_val.pt', weights_only=True)

X_test = torch.load(data_path + '/X_test.pt', weights_only=True)
y_test = torch.load(data_path + '/y_test.pt', weights_only=True)
test_mapping = pd.read_csv(data_path + '/test_mapping.csv')

In [5]:
print(f"X_train shape: {X_train.shape}")
print(f"y_train shape: {y_train.shape}")
print(f"X_val shape: {X_val.shape}")
print(f"y_val shape: {y_val.shape}")

X_train shape: torch.Size([185227, 5, 50])
y_train shape: torch.Size([185227, 1])
X_val shape: torch.Size([11384, 5, 50])
y_val shape: torch.Size([11384, 1])

In [6]:
# Find all test_mapping rows for Mohamed Salah
salah_mapping = test_mapping[test_mapping['name'] == 'mohamed_salah']

# Get the sequence indices for Salah
salah_sequence_indices = salah_mapping['sequence_idx'].values

# Extract the corresponding X_test data for Salah
salah_x_test = X_test[salah_sequence_indices]

# You can also get the corresponding y_test data
salah_y_test = y_test[salah_sequence_indices]

In [7]:
last_1_assists_idx = 2
last_1_goals_scored_idx = 7

In [8]:
#sanity check to see there is no data leakage
for i in range(salah_x_test.shape[0]):
    last_1_assists = salah_x_test[i, -1, last_1_assists_idx]
    last_1_goals_scored = salah_x_test[i, -1,  last_1_goals_scored_idx]
    
    print(f"Gameweek {i + 1}: Last 1 Assists: {last_1_assists}, Last 1 Goals Scored: {last_1_goals_scored}, Total Points: {salah_y_test[i]}")

Gameweek 1: Last 1 Assists: 0.0, Last 1 Goals Scored: 0.0, Total Points: tensor([14.])
Gameweek 2: Last 1 Assists: 0.25, Last 1 Goals Scored: 0.25, Total Points: tensor([10.])
Gameweek 3: Last 1 Assists: 0.0, Last 1 Goals Scored: 0.25, Total Points: tensor([17.])
Gameweek 4: Last 1 Assists: 0.5, Last 1 Goals Scored: 0.25, Total Points: tensor([2.])
Gameweek 5: Last 1 Assists: 0.0, Last 1 Goals Scored: 0.0, Total Points: tensor([6.])
Gameweek 6: Last 1 Assists: 0.25, Last 1 Goals Scored: 0.0, Total Points: tensor([10.])
Gameweek 7: Last 1 Assists: 0.0, Last 1 Goals Scored: 0.25, Total Points: tensor([3.])
Gameweek 8: Last 1 Assists: 0.0, Last 1 Goals Scored: 0.0, Total Points: tensor([12.])
Gameweek 9: Last 1 Assists: 0.25, Last 1 Goals Scored: 0.25, Total Points: tensor([10.])
Gameweek 10: Last 1 Assists: 0.0, Last 1 Goals Scored: 0.25, Total Points: tensor([9.])
Gameweek 11: Last 1 Assists: 0.0, Last 1 Goals Scored: 0.25, Total Points: tensor([14.])
Gameweek 12: Last 1 Assists: 0.25, Last 1 Goals Scored: 0.25, Total Points: tensor([13.])
Gameweek 13: Last 1 Assists: 0.0, Last 1 Goals Scored: 0.5, Total Points: tensor([13.])
Gameweek 14: Last 1 Assists: 0.25, Last 1 Goals Scored: 0.25, Total Points: tensor([18.])
Gameweek 15: Last 1 Assists: 0.25, Last 1 Goals Scored: 0.5, Total Points: tensor([13.])
Gameweek 16: Last 1 Assists: 0.25, Last 1 Goals Scored: 0.25, Total Points: tensor([5.])
Gameweek 17: Last 1 Assists: 0.25, Last 1 Goals Scored: 0.0, Total Points: tensor([21.])
Gameweek 18: Last 1 Assists: 0.5, Last 1 Goals Scored: 0.5, Total Points: tensor([9.])
Gameweek 19: Last 1 Assists: 0.0, Last 1 Goals Scored: 0.25, Total Points: tensor([16.])
Gameweek 20: Last 1 Assists: 0.5, Last 1 Goals Scored: 0.25, Total Points: tensor([7.])
Gameweek 21: Last 1 Assists: 0.0, Last 1 Goals Scored: 0.25, Total Points: tensor([2.])
Gameweek 22: Last 1 Assists: 0.0, Last 1 Goals Scored: 0.0, Total Points: tensor([3.])
Gameweek 23: Last 1 Assists: 0.0, Last 1 Goals Scored: 0.0, Total Points: tensor([8.])
Gameweek 24: Last 1 Assists: 0.0, Last 1 Goals Scored: 0.25, Total Points: tensor([16.])
Gameweek 25: Last 1 Assists: 0.0, Last 1 Goals Scored: 0.5, Total Points: tensor([8.])
Gameweek 26: Last 1 Assists: 0.0, Last 1 Goals Scored: 0.25, Total Points: tensor([14.])
Gameweek 27: Last 1 Assists: 0.25, Last 1 Goals Scored: 0.25, Total Points: tensor([6.])
Gameweek 28: Last 1 Assists: 0.25, Last 1 Goals Scored: 0.0, Total Points: tensor([15.])
Gameweek 29: Last 1 Assists: 0.0, Last 1 Goals Scored: 0.5, Total Points: tensor([12.])
Gameweek 30: Last 1 Assists: 0.25, Last 1 Goals Scored: 0.25, Total Points: tensor([3.])
Gameweek 31: Last 1 Assists: 0.0, Last 1 Goals Scored: 0.0, Total Points: tensor([2.])
Gameweek 32: Last 1 Assists: 0.0, Last 1 Goals Scored: 0.0, Total Points: tensor([6.])
Gameweek 33: Last 1 Assists: 0.25, Last 1 Goals Scored: 0.0, Total Points: tensor([3.])
Gameweek 34: Last 1 Assists: 0.0, Last 1 Goals Scored: 0.0, Total Points: tensor([8.])
Gameweek 35: Last 1 Assists: 0.0, Last 1 Goals Scored: 0.25, Total Points: tensor([2.])
Gameweek 36: Last 1 Assists: 0.0, Last 1 Goals Scored: 0.0, Total Points: tensor([2.])
Gameweek 37: Last 1 Assists: 0.0, Last 1 Goals Scored: 0.0, Total Points: tensor([2.])
Gameweek 38: Last 1 Assists: 0.0, Last 1 Goals Scored: 0.0, Total Points: tensor([10.])

In [10]:
best_model_data = torch.load("best_model.pth", map_location=torch.device('cpu'))

/var/folders/yv/683h12gj4mdc5txzm0lh6j0h0000gn/T/ipykernel_22626/2890380057.py:1: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  best_model_data = torch.load("best_model.pth", map_location=torch.device('cpu'))

In [11]:
print(best_model_data['hidden_dim'])
print(best_model_data['num_layers'])
print(best_model_data['num_fc_layers'])

64
1
3

In [12]:
model = AdvancedLSTM(
    hidden_dim=best_model_data['hidden_dim'],
    num_layers=best_model_data['num_layers'],
    input_dim= best_model_data['input_dim'],
    output_dim=1,
    num_fc_layers=best_model_data['num_fc_layers'],
) 
model.load_state_dict(best_model_data['model_state_dict'])

/opt/anaconda3/envs/fpl_helper/lib/python3.11/site-packages/torch/nn/modules/rnn.py:123: UserWarning: dropout option adds dropout after all but last recurrent layer, so non-zero dropout expects num_layers greater than 1, but got dropout=0.3 and num_layers=1
  warnings.warn(

In [13]:
#print number of parameters in the model
num_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
print(f"Number of parameters in the model: {num_params}")

Number of parameters in the model: 32417

In [14]:
model.eval()

AdvancedLSTM(
  (lstm): LSTM(50, 64, batch_first=True, dropout=0.3)
  (fc_layers): ModuleList(
    (0): Linear(in_features=64, out_features=32, bias=True)
    (1): Linear(in_features=32, out_features=16, bias=True)
    (2): Linear(in_features=16, out_features=1, bias=True)
  )
  (batch_norms): ModuleList(
    (0): BatchNorm1d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (1): BatchNorm1d(16, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  )
  (dropout): Dropout(p=0.3, inplace=False)
  (relu): ReLU()
)

In [15]:
print(X_train.shape)
print(X_val.shape)
print(X_test.shape)

torch.Size([185227, 5, 50])
torch.Size([11384, 5, 50])
torch.Size([11567, 5, 50])

In [16]:
test = pd.read_csv(data_path + '/test_data.csv')

In [17]:
predictions = model(X_test).detach().numpy()
print(predictions.shape)
print(y_test.shape)

(11567, 1)
torch.Size([11567, 1])

In [18]:
print(torch.mean(y_test))
print(torch.var(y_test))

tensor(2.7053)
tensor(8.3782)

In [19]:
print(np.mean(predictions))
print(np.var(predictions))

2.6885464
0.72525454

In [20]:
from sklearn.metrics import root_mean_squared_error, mean_absolute_error

rmse = root_mean_squared_error(y_test, predictions)
print(f"RMSE: {rmse}")

mae = mean_absolute_error(y_test, predictions)
print(f"MAE: {mae}")

RMSE: 2.781411647796631
MAE: 1.9658403396606445

In [21]:
X_test.shape

torch.Size([11567, 5, 50])

In [22]:
salah_y_test[0]

tensor([14.])

In [23]:
remaining_lagged_features = sorted(pickle.load(open(data_path + '/remaining_lagged_features.pkl', 'rb')))
remaining_lagged_features

['lagged_fixture_difficulty',
 'lagged_was_home',
 'last_1_assists',
 'last_1_bonus',
 'last_1_clean_sheets',
 'last_1_creativity',
 'last_1_goals_conceded',
 'last_1_goals_scored',
 'last_1_ict_index',
 'last_1_influence',
 'last_1_minutes',
 'last_1_red_cards',
 'last_1_result_encoded',
 'last_1_threat',
 'last_1_yellow_cards',
 'last_3_assists',
 'last_3_bonus',
 'last_3_clean_sheets',
 'last_3_creativity',
 'last_3_goals_conceded',
 'last_3_goals_scored',
 'last_3_ict_index',
 'last_3_influence',
 'last_3_minutes',
 'last_3_red_cards',
 'last_3_result_encoded',
 'last_3_threat',
 'last_3_yellow_cards',
 'last_5_assists',
 'last_5_bonus',
 'last_5_clean_sheets',
 'last_5_goals_conceded',
 'last_5_goals_scored',
 'last_5_influence',
 'last_5_red_cards',
 'last_5_result_encoded',
 'last_5_yellow_cards',
 'last_all_assists',
 'last_all_bonus',
 'last_all_clean_sheets',
 'last_all_creativity',
 'last_all_goals_conceded',
 'last_all_goals_scored',
 'last_all_ict_index',
 'last_all_influence',
 'last_all_red_cards',
 'last_all_result_encoded',
 'last_all_threat',
 'last_all_yellow_cards',
 'position_encoded']

In [24]:
for i in range(0, len(remaining_lagged_features)):
    if salah_x_test[0, -1, i] != 0:
        print(f"Feature {remaining_lagged_features[i]} is not zero")
        print("Value is ", salah_x_test[0, -1, i])
        print()

Feature lagged_fixture_difficulty is not zero
Value is  tensor(0.4000)

Feature position_encoded is not zero
Value is  tensor(2.)

In [25]:
salah_y_test[16]

tensor([21.])

In [26]:
test = pd.read_csv(data_path + '/test_data.csv')
salah_df = test[test['name'] == 'mohamed_salah']
salah_df[['name', 'GW', 'total_points', 'last_1_assists', 'last_1_goals_scored', 'last_1_ict_index']]

,name,GW,total_points,last_1_assists,last_1_goals_scored,last_1_ict_index
108,mohamed_salah,1.0,14.0,0.00,0.00,0.000000
420,mohamed_salah,2.0,10.0,0.25,0.25,0.424581
746,mohamed_salah,3.0,17.0,0.00,0.25,0.270950
1063,mohamed_salah,4.0,2.0,0.50,0.25,0.449721
1372,mohamed_salah,5.0,6.0,0.00,0.00,0.231844
1690,mohamed_salah,6.0,10.0,0.25,0.00,0.558659
1994,mohamed_salah,7.0,3.0,0.00,0.25,0.354749
2305,mohamed_salah,8.0,12.0,0.00,0.00,0.117318
2613,mohamed_salah,9.0,10.0,0.25,0.25,0.321229
2924,mohamed_salah,10.0,9.0,0.00,0.25,0.282123
3230,mohamed_salah,11.0,14.0,0.00,0.25,0.307263
3530,mohamed_salah,12.0,13.0,0.25,0.25,0.371508
3840,mohamed_salah,13.0,13.0,0.00,0.50,0.508380
4159,mohamed_salah,14.0,18.0,0.25,0.25,0.282123
4646,mohamed_salah,15.0,13.0,0.25,0.50,0.569832
4775,mohamed_salah,16.0,5.0,0.25,0.25,0.368715
5087,mohamed_salah,17.0,21.0,0.25,0.00,0.203911
5382,mohamed_salah,18.0,9.0,0.50,0.50,0.703911
5690,mohamed_salah,19.0,16.0,0.00,0.25,0.516760
5998,mohamed_salah,20.0,7.0,0.50,0.25,0.689944
6286,mohamed_salah,21.0,2.0,0.00,0.25,0.287709
6586,mohamed_salah,22.0,3.0,0.00,0.00,0.290503
6880,mohamed_salah,23.0,8.0,0.00,0.00,0.418994
7175,mohamed_salah,24.0,16.0,0.00,0.25,0.357542
7464,mohamed_salah,25.0,8.0,0.00,0.50,0.469274
7767,mohamed_salah,26.0,14.0,0.00,0.25,0.212291
8058,mohamed_salah,27.0,6.0,0.25,0.25,0.407821
8356,mohamed_salah,28.0,15.0,0.25,0.00,0.335196
8558,mohamed_salah,29.0,12.0,0.00,0.50,0.614525
8965,mohamed_salah,30.0,3.0,0.25,0.25,0.321229
9260,mohamed_salah,31.0,2.0,0.00,0.00,0.178771
9574,mohamed_salah,32.0,6.0,0.00,0.00,0.128492
9871,mohamed_salah,33.0,3.0,0.25,0.00,0.203911
10211,mohamed_salah,34.0,8.0,0.00,0.00,0.243017
10481,mohamed_salah,35.0,2.0,0.00,0.25,0.407821
10780,mohamed_salah,36.0,2.0,0.00,0.00,0.139665
11082,mohamed_salah,37.0,2.0,0.00,0.00,0.150838
11387,mohamed_salah,38.0,10.0,0.00,0.00,0.282123

In [33]:
for i in range(0, len(salah_x_test)):
    input_to_game = salah_x_test[i].unsqueeze(0)
    print(f"Gameweek {i + 1}:")
    print("prediction", model(input_to_game).detach().numpy())
    print("actual", salah_y_test[i].item())

Gameweek 1:
prediction [[1.7004305]]
actual 14.0
Gameweek 2:
prediction [[3.6332295]]
actual 10.0
Gameweek 3:
prediction [[3.2940903]]
actual 17.0
Gameweek 4:
prediction [[4.2217674]]
actual 2.0
Gameweek 5:
prediction [[4.6880326]]
actual 6.0
Gameweek 6:
prediction [[5.8495173]]
actual 10.0
Gameweek 7:
prediction [[5.89323]]
actual 3.0
Gameweek 8:
prediction [[6.3016515]]
actual 12.0
Gameweek 9:
prediction [[5.7335]]
actual 10.0
Gameweek 10:
prediction [[6.1430726]]
actual 9.0
Gameweek 11:
prediction [[5.4677267]]
actual 14.0
Gameweek 12:
prediction [[5.6366725]]
actual 13.0
Gameweek 13:
prediction [[6.3887467]]
actual 13.0
Gameweek 14:
prediction [[6.517064]]
actual 18.0
Gameweek 15:
prediction [[7.2635403]]
actual 13.0
Gameweek 16:
prediction [[7.409186]]
actual 5.0
Gameweek 17:
prediction [[6.685003]]
actual 21.0
Gameweek 18:
prediction [[7.4882407]]
actual 9.0
Gameweek 19:
prediction [[6.9127555]]
actual 16.0
Gameweek 20:
prediction [[7.699634]]
actual 7.0
Gameweek 21:
prediction [[7.537564]]
actual 2.0
Gameweek 22:
prediction [[8.221453]]
actual 3.0
Gameweek 23:
prediction [[8.151192]]
actual 8.0
Gameweek 24:
prediction [[7.6321754]]
actual 16.0
Gameweek 25:
prediction [[8.3574505]]
actual 8.0
Gameweek 26:
prediction [[7.4838376]]
actual 14.0
Gameweek 27:
prediction [[8.348623]]
actual 6.0
Gameweek 28:
prediction [[7.4122562]]
actual 15.0
Gameweek 29:
prediction [[7.502074]]
actual 12.0
Gameweek 30:
prediction [[8.461426]]
actual 3.0
Gameweek 31:
prediction [[7.7145553]]
actual 2.0
Gameweek 32:
prediction [[8.634863]]
actual 6.0
Gameweek 33:
prediction [[7.35458]]
actual 3.0
Gameweek 34:
prediction [[7.833371]]
actual 8.0
Gameweek 35:
prediction [[7.512524]]
actual 2.0
Gameweek 36:
prediction [[8.892582]]
actual 2.0
Gameweek 37:
prediction [[8.174652]]
actual 2.0
Gameweek 38:
prediction [[9.141066]]
actual 10.0

In [34]:
scores, total_score = get_season_performance(
    y_test=y_test,
    predictions=predictions,
    remaining_lagged_features=remaining_lagged_features
)

Players with NaN total_points_last_season: []
Number of NaN values remaining: 0
0.0 :  daniel_bentley
1.0 :  luke_thomas
2.0 :  matheus_franca_de_oliveira
3.0 :  daniel_jebbison
Bench players: ['daniel_bentley', 'luke_thomas', 'matheus_franca_de_oliveira', 'daniel_jebbison']
Bench cost: 167
length available players df 562
Available cash: 833
Decision variables: [aaron_cresswell, aaron_ramsdale, aaron_wan_bissaka, abdoulaye_doucoure, abdukodir_khusanov, abdul_fatawu, adam_armstrong, adam_lallana, adam_smith, adam_webster, adam_wharton, adama_traore, albert_gronbaek, alejandro_garnacho, alex_iwobi, alex_mccarthy, alex_moreno_lopera, alex_palmer, alex_scott, alexander_isak, alexis_mac_allister, alfie_dorrington, alfie_pond, ali_al_hamadi, alisson_ramses_becker, alphonse_areola, altay_bayindir, amad_diallo, amadou_onana, andre_onana, andre_trindade_da_costa_neto, andreas_hoelgebaum_pereira, andres_garcia, andrew_robertson, andy_irving, anthony_elanga, anthony_gordon, antoine_semenyo, antonee_robinson, antonin_kinsky, antony_matheus_dos_santos, archie_gray, arijanet_muric, armando_broja, armel_bella_kotchap, asher_agbinone, ashley_young, axel_disasi, axel_tuanzebe, ayden_heaven, bart_verbruggen, ben_brereton_diaz, ben_chilwell, ben_davies, ben_godfrey, ben_johnson, ben_mee, ben_winterburn, benjamin_white, benoit_badiashile, bernardo_veiga_de_carvalho_e_silva, bernd_leno, bilal_el_khannouss, billy_gilmour, bobby_de_cordova_reid, boubacar_kamara, boubacar_traore, boubakary_soumare, brajan_gruda, brandon_austin, brennan_johnson, bruno_borges_fernandes, bruno_guimaraes_rodriguez_moura, bryan_mbeumo, bukayo_saka, caleb_kporha, caleb_okoli, callum_hudson_odoi, callum_wilson, calvin_bassey, cameron_archer, cameron_burgess, caoimhin_kelleher, carlos_alcaraz_duran, carlos_baleba, carlos_henrique_casimiro, carlos_roberto_forbs_borges, carlos_soler, carlos_vinicius_alves_morais, chadi_riad_dnanou, charlie_taylor, cheick_doucoure, chido_obi_martin, chiedozie_ogbene, chris_richards, chris_wood, christian_eriksen, christian_norgaard, christian_walton, christopher_nkunku, claudio_echeverri, cody_gakpo, cole_palmer, conor_bradley, conor_chaplin, conor_coady, conor_townsend, craig_dawson, cristian_romero, crysencio_summerville, curtis_jones, daichi_kamada, dan_burn, dane_scarlett, dango_ouattara, daniel_bentley, daniel_castelo_podence, daniel_jebbison, daniel_munoz, danilo_dos_santos_de_oliveira, danny_ings, danny_ward, danny_welbeck, dara_o'shea, darwin_nunez_ribeiro, david_brooks, david_raya_martin, dean_henderson, dean_huijsen, declan_rice, dejan_kulusevski, destiny_udogie, diego_carlos_santos_silva, diego_gomez, diogo_dalot_teixeira, diogo_teixeira_da_silva, divin_mubama, djed_spence, dominic_calvert_lewin, dominic_solanke_mitchell, dominik_szoboszlai, donyell_malen, dwight_mcneil, eberechi_eze, eddie_nketiah, ederson_santana_de_moraes, edson_alvarez_velazquez, eiran_cashin, elliot_anderson, emerson_palmieri_dos_santos, emil_krafth, emile_smith_rowe, emiliano_buendia_stati, emiliano_martinez_romero, emmanuel_agbadou, endo_wataru, enes_unal, enzo_fernandez, eric_da_silva_moreira, erling_haaland, ethan_nwaneri, ethan_pinnock, evan_ferguson, ezri_konsa_ngoyo, fabian_schar, fabio_freitas_gouveia_carvalho, facundo_buonanotte, federico_chiesa, felipe_rodrigues_da_silva, ferdi_kadioglu, filip_jorgensen, flynn_downes, francisco_evanilson_de_lima_barbosa, francisco_jorge_tomas_oliveira, frank_onyeka, fraser_forster, gabriel_dos_santos_magalhaes, gabriel_fernando_de_jesus, gabriel_martinelli_silva, george_edmundson, george_hirst, georginio_rutter, goncalo_manuel_ganchinho_guedes, guglielmo_vicario, guido_rodriguez, gustavo_nunes_fernandes_gomes, hakon_valdimarsson, hamza_choudhury, harrison_armstrong, harrison_reed, harry_amass, harry_clarke, harry_howell, harry_maguire, harry_toffolo, harry_wilson, harry_winks, harvey_barnes, harvey_elliott, hwang_hee_chan, ian_maatsen, ibrahim_sangare, ibrahima_konate, idrissa_gueye, igor_julio_dos_santos_de_paulo, igor_thiago_nascimento_rodrigues, iliman_ndiaye, ilkay_gundogan, illia_zabarnyi, ismaila_sarr, issa_diop, jack_clarke, jack_grealish, jack_harrison, jack_hinshelwood, jack_stephens, jack_taylor, jacob_greaves, jacob_murphy, jacob_ramsey, jaden_philogene, jadon_sancho, jahmai_simpson_pusey, jake_evans, jake_o'brien, jakub_kiwior, jakub_moder, jakub_stolarczyk, james_bree, james_garner, james_hill, james_justin, james_maddison, james_mcatee, james_milner, james_tarkowski, james_ward_prowse, jamie_vardy, jan_bednarek, jan_paul_van_hecke, jannik_vestergaard, jarell_quansah, jarrad_branthwaite, jarrod_bowen, jason_steele, jay_robinson, jay_stansfield, jayden_danns, jayden_meghoma, jean_clair_todibo, jean_philippe_mateta, jean_ricner_bellegarde, jefferson_lerma_solis, jeffrey_schlupp, jens_cajuste, jeremy_doku, jeremy_monga, jeremy_sarmiento_morante, jesper_lindstrom, jhon_duran, joachim_andersen, joachim_kayi_sanda, joao_felix_sequeira, joao_pedro_ferreira_silva, joao_pedro_junqueira_de_jesus, joao_victor_gomes_da_silva, joe_aribo, joe_gomez, joe_lumley, joe_willock, joel_veltman, joel_ward, joelinton_cassio_apolinario_de_lira, john_mcginn, john_stones, jonny_evans, jordan_ayew, jordan_pickford, jorge_cuenca_barreno, jorge_luiz_frello_filho, jorgen_strand_larsen, jose_malheiro_de_sa, josh_acheampong, josh_king, joshua_zirkzee, josko_gvardiol, julian_araujo_zuniga, julio_enciso, julio_soler, jurrien_timber, justin_devenny, justin_kluivert, kaelan_casey, kai_havertz, kalvin_phillips, kamaldeen_sulemana, kasey_mcateer, keane_lewis_potter, kenny_tete, kepa_arrizabalaga, kevin_danso, kevin_de_bruyne, kevin_schade, kieran_tierney, kieran_trippier, kiernan_dewsbury_hall, kim_ji_soo, kobbie_mainoo, konstantinos_mavropanos, konstantinos_tsimikas, kosta_nedeljkovic, kristoffer_ajer, kyle_walker, kyle_walker_peters, lamare_bogarde, leandro_trossard, leif_davis, leny_yoro, leon_bailey, lesley_ugochukwu, levi_colwill, lewis_cook, lewis_dunk, lewis_hall, lewis_miley, lewis_orford, liam_delap, lisandro_martinez, lloyd_kelly, lucas_bergvall, lucas_digne, lucas_tolentino_coelho_de_lima, luis_diaz, luis_guilherme_lira_dos_santos, luis_sinisterra, lukasz_fabianski, luke_shaw, luke_thomas, luke_woolfenden, mads_hermansen, mads_roerslev_rasmussen, malo_gusto, manuel_akanji, manuel_ugarte, marc_cucurella_saseta, marc_guehi, marc_guiu_paz, marco_asensio, marcos_senesi, marcus_myers_harness, marcus_rashford, marcus_tavernier, mario_lemina, mark_flekken, mark_travers, marshall_munetsi, martial_godo, martin_dubravka, martin_odegaard, mason_holgate, mason_mount, massimo_luongo, mateo_kovacic, mateus_goncalo_espanha_fernandes, mateus_mane, matheus_franca_de_oliveira, matheus_luiz_nunes, matheus_santos_carneiro_da_cunha, mathias_jensen, mathis_amougou, mathys_tel, mats_wieffer, matt_doherty, matt_o'riley, matt_targett, matthijs_de_ligt, matty_cash, matz_sels, max_aarons, max_kilman, maxence_lacroix, maxwel_cornet, michael_golding, michael_kayode, michael_keane, michail_antonio, micky_van_de_ven, miguel_almiron_rejala, mikel_merino, mikey_moore, mikkel_damsgaard, milos_kerkez, mitoma_kaoru, mohamed_salah, mohammed_kudus, moises_caicedo_corozo, morgan_gibbs_white, morgan_rogers, murillo_santiago_costa_dos_santos, mykhailo_mudryk, myles_lewis_skelly, nasser_djiga, nathan_ake, nathan_broadhead, nathan_butler_oyedeji, nathan_collins, nathan_patterson, nathan_wood_gordon, nathaniel_clyne, neco_williams, nelson_cabral_semedo, nick_pope, niclas_fullkrug, nico_gonzalez, nico_o'reilly, nicolas_dominguez, nicolas_jackson, nikola_milenkovic, noni_madueke, norberto_bercique_gomes_betuncal, norberto_murara_neto, noussair_mazraoui, odsonne_edouard, ola_aina, olabade_aluko, oleksandr_zinchenko, oliver_skipp, ollie_scarles, ollie_watkins, omar_marmoush, omari_giraud_hutchinson, orel_mangala, oscar_bobb, pablo_sarabia, pape_matar_sarr, paris_maghoma, patrick_dorgu, patson_daka, pau_torres, paul_onuachu, pedro_cardoso_de_lima, pedro_lomba_neto, pedro_porro, pervis_estupinan, phil_foden, philip_billing, radu_dragusin, raheem_sterling, ramon_sosa, rasmus_hojlund, raul_jimenez, rayan_ait_nouri, reece_james, reiss_nelson, remy_rees_dottin, renato_palma_veiga, ricardo_barbosa_pereira, riccardo_calafiori, richarlison_de_andrade, rico_henry, rico_lewis, robert_sanchez, robin_olsen, rodrigo_'rodri'_hernandez, rodrigo_bentancur, rodrigo_martins_gomes, rodrigo_muniz_carvalho, romain_esse, roman_dixon, romeo_lavia, ronnie_edwards, ross_barkley, ross_stewart, ruben_gato_alves_dias, ryan_christie, ryan_fraser, ryan_gravenberch, ryan_manning, ryan_sessegnon, ryan_trevitt, ryan_yates, sam_johnstone, sam_morsy, sam_szmodics, samuel_amo_ameyaw, samuel_edozie, sander_berge, sandro_tonali, santiago_bueno, sasa_lukic, savio_'savinho'_moreira_de_oliveira, scott_mctominay, seamus_coleman, sean_longstaff, sepp_van_den_berg, sergio_reguilon, shumaira_mheuka, simon_adingra, solly_march, son_heung_min, stefan_ortega_moreno, stephy_mavididi, sugawara_yukinari, sven_botman, taiwo_awoniyi, tariq_lamptey, taylor_harwood_bellis, thomas_partey, tim_iroegbunam, timo_werner, timothy_castagne, tino_livramento, toby_collyer, tom_cairney, tom_king, tomas_soucek, tomiyasu_takehiro, tommy_doyle, tosin_adarabioyo, toti_antonio_gomes, trent_alexander_arnold, trevoh_chalobah, tyler_adams, tyler_dibling, tyler_fredricson, tyrell_malacia, tyrick_mitchell, tyrique_george, tyrone_mings, victor_kristiansen, victor_lindelof, virgil_van_dijk, vitalii_mykolenko, vitaly_janelt, vitezslav_jaros, vitor_de_oliveira_nunes_dos_reis, vladimir_coufal, welington_damascena_santos, wes_burns, wesley_fofana, wilfred_ndidi, will_alves, will_hughes, will_lankshear, will_smallbone, william_osula, william_saliba, willian_borges_da_silva, willy_boly, wilson_odobert, wout_faes, woyo_coulibaly, yankuba_minteh, yasin_ayari, yehor_yarmoliuk, yerson_mosquera, yoane_wissa, youri_tielemans, youssef_ramalho_chermiti, yunus_emre_konak, yves_bissouma, zain_silcott_duberry]

In [35]:
scores

,GW,player_in,player_out,total_score
0,1.0,,,33.0
1,2.0,danny_welbeck,jean_philippe_mateta,72.0
2,3.0,pedro_porro,william_saliba,33.0
3,4.0,luis_diaz,son_heung_min,47.0
4,5.0,mohamed_salah,phil_foden,59.0
5,6.0,matheus_santos_carneiro_da_cunha,danny_welbeck,80.0
6,7.0,,,60.0
7,8.0,ashley_young,joachim_andersen,41.0
8,9.0,danny_welbeck,matheus_santos_carneiro_da_cunha,68.0
9,10.0,rayan_ait_nouri,jarrad_branthwaite,38.0
10,11.0,josko_gvardiol,benjamin_white,54.0
11,12.0,chris_wood,danny_welbeck,81.0
12,13.0,leif_davis,rayan_ait_nouri,78.0
13,14.0,matheus_santos_carneiro_da_cunha,chris_wood,91.0
14,15.0,,,57.0
15,16.0,alexander_isak,ollie_watkins,65.0
16,17.0,milos_kerkez,ashley_young,97.0
17,18.0,ola_aina,leif_davis,72.0
18,19.0,lewis_hall,milos_kerkez,82.0
19,20.0,nikola_milenkovic,pedro_porro,52.0
20,21.0,dominic_solanke_mitchell,matheus_santos_carneiro_da_cunha,57.0
21,22.0,pedro_porro,nikola_milenkovic,30.0
22,23.0,antonee_robinson,pedro_porro,52.0
23,24.0,,,63.0
24,25.0,daniel_munoz,antonee_robinson,43.0
25,26.0,,,70.0
26,27.0,,,43.0
27,28.0,dean_huijsen,daniel_munoz,51.0
28,29.0,gabriel_dos_santos_magalhaes,ola_aina,43.0
29,30.0,djed_spence,dean_huijsen,50.0
30,31.0,daniel_munoz,josko_gvardiol,32.0
31,32.0,ryan_sessegnon,djed_spence,43.0
32,33.0,,,32.0
33,34.0,,,55.0
34,35.0,,,28.0
35,36.0,tyrone_mings,ryan_sessegnon,38.0
36,37.0,matheus_santos_carneiro_da_cunha,dominic_solanke_mitchell,18.0
37,38.0,milos_kerkez,daniel_munoz,47.0

In [36]:
total_score.item()

2055.0

In [37]:
scores, total_score = season_performance_with_unlimited_transfers(
    y_test=y_test,
    predictions=predictions,
    remaining_lagged_features=remaining_lagged_features
)

Players with NaN total_points_last_season: []
Number of NaN values remaining: 0
0.0 :  daniel_bentley
1.0 :  luke_thomas
2.0 :  matheus_franca_de_oliveira
3.0 :  daniel_jebbison
Bench players: ['daniel_bentley', 'luke_thomas', 'matheus_franca_de_oliveira', 'daniel_jebbison']
Bench cost: 167
Simulating season with unlimited transfers for 38 gameweeks
Available budget per gameweek: 833

--- Gameweek 1.0 ---
Players available for GW 1.0: 316
Welcome to the CBC MILP Solver
Version: 2.10.3
Build Date: Dec 15 2019

command line - /opt/anaconda3/envs/fpl_helper/lib/python3.11/site-packages/pulp/apis/../solverdir/cbc/osx/i64/cbc /var/folders/yv/683h12gj4mdc5txzm0lh6j0h0000gn/T/2bcbe6b0019b48ca9f01b605c5a78d31-pulp.mps -max -timeMode elapsed -branch -printingOptions all -solution /var/folders/yv/683h12gj4mdc5txzm0lh6j0h0000gn/T/2bcbe6b0019b48ca9f01b605c5a78d31-pulp.sol (default strategy 1)
At line 2 NAME          MODEL
At line 3 ROWS
At line 30 COLUMNS
At line 1927 RHS
At line 1953 BOUNDS
At line 2270 ENDATA
Problem MODEL has 25 rows, 316 columns and 948 elements
Coin0008I MODEL read with 0 errors
Option for timeMode changed from cpu to elapsed
Continuous objective value is 19.4876 - 0.00 seconds
Cgl0004I processed model has 25 rows, 176 columns (176 integer (106 of which binary)) and 528 elements
Cbc0038I Initial state - 0 integers unsatisfied sum - 0
Cbc0038I Solution found of -19.4876
Cbc0038I Cleaned solution of -19.4876
Cbc0038I Before mini branch and bound, 176 integers at bound fixed and 0 continuous of which 3 were internal integer and 0 internal continuous
Cbc0038I Mini branch and bound did not improve solution (0.00 seconds)
Cbc0038I After 0.00 seconds - Feasibility pump exiting with objective of -19.4876 - took 0.00 seconds
Cbc0012I Integer solution of -19.487605 found by feasibility pump after 0 iterations and 0 nodes (0.00 seconds)
Cbc0001I Search completed - best objective -19.487604618072, took 0 iterations and 0 nodes (0.00 seconds)
Cbc0035I Maximum depth 0, 0 variables fixed on reduced cost
Cuts at root node changed objective from -19.4876 to -19.4876
Probing was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Gomory was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Knapsack was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Clique was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
MixedIntegerRounding2 was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
FlowCover was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
TwoMirCuts was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
ZeroHalf was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)

Result - Optimal solution found

Objective value:                19.48760462
Enumerated nodes:               0
Total iterations:               0
Time (CPU seconds):             0.00
Time (Wallclock seconds):       0.00

Option for printingOptions changed from normal to all
Total time (CPU seconds):       0.01   (Wallclock seconds):       0.01

                                name  actual  predicted
591                   cameron_archer     1.0   1.712254
1324                 justin_kluivert     0.0   1.741691
1358            norberto_murara_neto     4.0   1.803504
6054                   manuel_akanji     6.0   1.796351
6356                      rico_lewis     6.0   1.796351
6460           ruben_gato_alves_dias     6.0   1.796351
8090                  adam_armstrong     2.0   1.712254
8344               sugawara_yukinari     1.0   1.796351
9453  francisco_jorge_tomas_oliveira     1.0   1.777499
9766          daniel_castelo_podence     1.0   1.777499
9768           rodrigo_martins_gomes     2.0   1.777499
GW 1.0 optimal team: ['adam_armstrong', 'cameron_archer', 'daniel_castelo_podence', 'francisco_jorge_tomas_oliveira', 'justin_kluivert', 'manuel_akanji', 'norberto_murara_neto', 'rico_lewis', 'rodrigo_martins_gomes', 'ruben_gato_alves_dias', 'sugawara_yukinari']
GW 1.0 score: 36.0
Team cost: 560

--- Gameweek 2.0 ---
Players available for GW 2.0: 319
Welcome to the CBC MILP Solver
Version: 2.10.3
Build Date: Dec 15 2019

command line - /opt/anaconda3/envs/fpl_helper/lib/python3.11/site-packages/pulp/apis/../solverdir/cbc/osx/i64/cbc /var/folders/yv/683h12gj4mdc5txzm0lh6j0h0000gn/T/783a96c90fb54673a4fd81c0ff4fba5f-pulp.mps -max -timeMode elapsed -branch -printingOptions all -solution /var/folders/yv/683h12gj4mdc5txzm0lh6j0h0000gn/T/783a96c90fb54673a4fd81c0ff4fba5f-pulp.sol (default strategy 1)
At line 2 NAME          MODEL
At line 3 ROWS
At line 30 COLUMNS
At line 1945 RHS
At line 1971 BOUNDS
At line 2291 ENDATA
Problem MODEL has 25 rows, 319 columns and 957 elements
Coin0008I MODEL read with 0 errors
Option for timeMode changed from cpu to elapsed
Continuous objective value is 32.6284 - 0.00 seconds
Cgl0004I processed model has 25 rows, 318 columns (318 integer (317 of which binary)) and 954 elements
Cbc0038I Initial state - 0 integers unsatisfied sum - 0
Cbc0038I Solution found of -32.6284
Cbc0038I Cleaned solution of -32.6284
Cbc0038I Before mini branch and bound, 318 integers at bound fixed and 0 continuous
Cbc0038I Mini branch and bound did not improve solution (0.00 seconds)
Cbc0038I After 0.00 seconds - Feasibility pump exiting with objective of -32.6284 - took 0.00 seconds
Cbc0012I Integer solution of -32.628443 found by feasibility pump after 0 iterations and 0 nodes (0.00 seconds)
Cbc0001I Search completed - best objective -32.62844324112, took 0 iterations and 0 nodes (0.00 seconds)
Cbc0035I Maximum depth 0, 0 variables fixed on reduced cost
Cuts at root node changed objective from -32.6284 to -32.6284
Probing was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Gomory was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Knapsack was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Clique was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
MixedIntegerRounding2 was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
FlowCover was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
TwoMirCuts was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
ZeroHalf was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)

Result - Optimal solution found

Objective value:                32.62844324
Enumerated nodes:               0
Total iterations:               0
Time (CPU seconds):             0.00
Time (Wallclock seconds):       0.00

Option for printingOptions changed from normal to all
Total time (CPU seconds):       0.01   (Wallclock seconds):       0.01

                           name  actual  predicted
46                  kai_havertz     2.0   3.075142
364                 bukayo_saka     6.0   3.181031
1423            antoine_semenyo     5.0   3.174914
2418               mitoma_kaoru     6.0   3.114776
2566              danny_welbeck     9.0   3.434124
5458     trent_alexander_arnold     6.0   2.476320
5814              mohamed_salah    10.0   3.633230
6184  ederson_santana_de_moraes     2.0   2.470437
6258             josko_gvardiol     2.0   2.525310
8673                pedro_porro     6.0   3.057601
9690            yerson_mosquera    -2.0   2.485560
GW 2.0 optimal team: ['antoine_semenyo', 'bukayo_saka', 'danny_welbeck', 'ederson_santana_de_moraes', 'josko_gvardiol', 'kai_havertz', 'mitoma_kaoru', 'mohamed_salah', 'pedro_porro', 'trent_alexander_arnold', 'yerson_mosquera']
GW 2.0 score: 62.0
Team cost: 760

--- Gameweek 3.0 ---
Players available for GW 3.0: 312
Welcome to the CBC MILP Solver
Version: 2.10.3
Build Date: Dec 15 2019

command line - /opt/anaconda3/envs/fpl_helper/lib/python3.11/site-packages/pulp/apis/../solverdir/cbc/osx/i64/cbc /var/folders/yv/683h12gj4mdc5txzm0lh6j0h0000gn/T/aa8fcd68d9544456b18d876ae68a7f3f-pulp.mps -max -timeMode elapsed -branch -printingOptions all -solution /var/folders/yv/683h12gj4mdc5txzm0lh6j0h0000gn/T/aa8fcd68d9544456b18d876ae68a7f3f-pulp.sol (default strategy 1)
At line 2 NAME          MODEL
At line 3 ROWS
At line 30 COLUMNS
At line 1903 RHS
At line 1929 BOUNDS
At line 2242 ENDATA
Problem MODEL has 25 rows, 312 columns and 936 elements
Coin0008I MODEL read with 0 errors
Option for timeMode changed from cpu to elapsed
Continuous objective value is 35.9216 - 0.00 seconds
Cgl0004I processed model has 25 rows, 310 columns (310 integer (308 of which binary)) and 930 elements
Cbc0038I Initial state - 0 integers unsatisfied sum - 0
Cbc0038I Solution found of -35.9216
Cbc0038I Cleaned solution of -35.9216
Cbc0038I Before mini branch and bound, 310 integers at bound fixed and 0 continuous
Cbc0038I Mini branch and bound did not improve solution (0.00 seconds)
Cbc0038I After 0.00 seconds - Feasibility pump exiting with objective of -35.9216 - took 0.00 seconds
Cbc0012I Integer solution of -35.921592 found by feasibility pump after 0 iterations and 0 nodes (0.00 seconds)
Cbc0001I Search completed - best objective -35.92159223556499, took 0 iterations and 0 nodes (0.00 seconds)
Cbc0035I Maximum depth 0, 0 variables fixed on reduced cost
Cuts at root node changed objective from -35.9216 to -35.9216
Probing was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Gomory was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Knapsack was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Clique was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
MixedIntegerRounding2 was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
FlowCover was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
TwoMirCuts was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
ZeroHalf was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)

Result - Optimal solution found

Objective value:                35.92159224
Enumerated nodes:               0
Total iterations:               0
Time (CPU seconds):             0.00
Time (Wallclock seconds):       0.00

Option for printingOptions changed from normal to all
Total time (CPU seconds):       0.01   (Wallclock seconds):       0.01

                   name  actual  predicted
292   david_raya_martin     2.0   2.620353
365         bukayo_saka     6.0   3.551782
1542   marcus_tavernier     2.0   3.403585
2938       noni_madueke     2.0   3.825902
2981    nicolas_jackson     6.0   3.247921
3038        cole_palmer     6.0   3.630928
5901   andrew_robertson     6.0   3.020101
6296     erling_haaland    17.0   3.377449
8674        pedro_porro     1.0   3.093950
8726    cristian_romero     1.0   3.090192
9173         max_kilman     0.0   3.059431
GW 3.0 optimal team: ['andrew_robertson', 'bukayo_saka', 'cole_palmer', 'cristian_romero', 'david_raya_martin', 'erling_haaland', 'marcus_tavernier', 'max_kilman', 'nicolas_jackson', 'noni_madueke', 'pedro_porro']
GW 3.0 score: 66.0
Team cost: 814

--- Gameweek 4.0 ---
Players available for GW 4.0: 315
Welcome to the CBC MILP Solver
Version: 2.10.3
Build Date: Dec 15 2019

command line - /opt/anaconda3/envs/fpl_helper/lib/python3.11/site-packages/pulp/apis/../solverdir/cbc/osx/i64/cbc /var/folders/yv/683h12gj4mdc5txzm0lh6j0h0000gn/T/70381ad7ed3a4d6a99a9b8d9367f99f6-pulp.mps -max -timeMode elapsed -branch -printingOptions all -solution /var/folders/yv/683h12gj4mdc5txzm0lh6j0h0000gn/T/70381ad7ed3a4d6a99a9b8d9367f99f6-pulp.sol (default strategy 1)
At line 2 NAME          MODEL
At line 3 ROWS
At line 30 COLUMNS
At line 1921 RHS
At line 1947 BOUNDS
At line 2263 ENDATA
Problem MODEL has 25 rows, 315 columns and 945 elements
Coin0008I MODEL read with 0 errors
Option for timeMode changed from cpu to elapsed
Continuous objective value is 39.4792 - 0.00 seconds
Cgl0004I processed model has 25 rows, 313 columns (313 integer (311 of which binary)) and 939 elements
Cbc0038I Initial state - 0 integers unsatisfied sum - 0
Cbc0038I Solution found of -39.4792
Cbc0038I Cleaned solution of -39.4792
Cbc0038I Before mini branch and bound, 313 integers at bound fixed and 0 continuous
Cbc0038I Mini branch and bound did not improve solution (0.00 seconds)
Cbc0038I After 0.00 seconds - Feasibility pump exiting with objective of -39.4792 - took 0.00 seconds
Cbc0012I Integer solution of -39.479192 found by feasibility pump after 0 iterations and 0 nodes (0.00 seconds)
Cbc0001I Search completed - best objective -39.479192256929, took 0 iterations and 0 nodes (0.00 seconds)
Cbc0035I Maximum depth 0, 0 variables fixed on reduced cost
Cuts at root node changed objective from -39.4792 to -39.4792
Probing was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Gomory was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Knapsack was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Clique was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
MixedIntegerRounding2 was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
FlowCover was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
TwoMirCuts was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
ZeroHalf was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)

Result - Optimal solution found

Objective value:                39.47919226
Enumerated nodes:               0
Total iterations:               0
Time (CPU seconds):             0.00
Time (Wallclock seconds):       0.00

Option for printingOptions changed from normal to all
Total time (CPU seconds):       0.01   (Wallclock seconds):       0.01

                         name  actual  predicted
366               bukayo_saka     7.0   4.278582
1543         marcus_tavernier     3.0   3.722082
2982          nicolas_jackson     1.0   3.576903
3039              cole_palmer     3.0   3.920528
3380           dean_henderson     1.0   3.125334
5460   trent_alexander_arnold     1.0   3.090797
5816            mohamed_salah     2.0   4.221767
5902         andrew_robertson     1.0   3.281590
8347        sugawara_yukinari     1.0   3.219890
8675              pedro_porro     2.0   3.511131
11409           omar_marmoush     2.0   3.530589
GW 4.0 optimal team: ['andrew_robertson', 'bukayo_saka', 'cole_palmer', 'dean_henderson', 'marcus_tavernier', 'mohamed_salah', 'nicolas_jackson', 'omar_marmoush', 'pedro_porro', 'sugawara_yukinari', 'trent_alexander_arnold']
GW 4.0 score: 31.0
Team cost: 805

--- Gameweek 5.0 ---
Players available for GW 5.0: 312
Welcome to the CBC MILP Solver
Version: 2.10.3
Build Date: Dec 15 2019

command line - /opt/anaconda3/envs/fpl_helper/lib/python3.11/site-packages/pulp/apis/../solverdir/cbc/osx/i64/cbc /var/folders/yv/683h12gj4mdc5txzm0lh6j0h0000gn/T/19848682ceff4feabf58299b78c996f7-pulp.mps -max -timeMode elapsed -branch -printingOptions all -solution /var/folders/yv/683h12gj4mdc5txzm0lh6j0h0000gn/T/19848682ceff4feabf58299b78c996f7-pulp.sol (default strategy 1)
At line 2 NAME          MODEL
At line 3 ROWS
At line 30 COLUMNS
At line 1903 RHS
At line 1929 BOUNDS
At line 2242 ENDATA
Problem MODEL has 25 rows, 312 columns and 936 elements
Coin0008I MODEL read with 0 errors
Option for timeMode changed from cpu to elapsed
Continuous objective value is 41.0505 - 0.00 seconds
Cgl0004I processed model has 25 rows, 311 columns (311 integer (310 of which binary)) and 933 elements
Cbc0038I Initial state - 2 integers unsatisfied sum - 0.12
Cbc0038I Solution found of -41.05
Cbc0038I Cleaned solution of -41.05
Cbc0038I Before mini branch and bound, 309 integers at bound fixed and 0 continuous
Cbc0038I Full problem 25 rows 311 columns, reduced to 0 rows 0 columns
Cbc0038I Mini branch and bound did not improve solution (0.01 seconds)
Cbc0038I Round again with cutoff of -41.0501
Cbc0038I Reduced cost fixing fixed 306 variables on major pass 2
Cbc0038I Pass   1: suminf.    0.01432 (2) obj. -41.0501 iterations 1
Cbc0038I Pass   2: suminf.    0.12000 (2) obj. -41.0505 iterations 1
Cbc0038I Pass   3: suminf.    0.12000 (2) obj. -41.0505 iterations 0
Cbc0038I Pass   4: suminf.    0.01432 (2) obj. -41.0501 iterations 1
Cbc0038I Pass   5: suminf.    0.12000 (2) obj. -41.0505 iterations 1
Cbc0038I Pass   6: suminf.    0.01432 (2) obj. -41.0501 iterations 1
Cbc0038I Pass   7: suminf.    0.01432 (2) obj. -41.0501 iterations 0
Cbc0038I Pass   8: suminf.    0.01432 (2) obj. -41.0501 iterations 0
Cbc0038I Pass   9: suminf.    0.01432 (2) obj. -41.0501 iterations 0
Cbc0038I Pass  10: suminf.    0.01432 (2) obj. -41.0501 iterations 0
Cbc0038I Pass  11: suminf.    0.01432 (2) obj. -41.0501 iterations 0
Cbc0038I Pass  12: suminf.    0.01432 (2) obj. -41.0501 iterations 0
Cbc0038I Pass  13: suminf.    0.01432 (2) obj. -41.0501 iterations 0
Cbc0038I Pass  14: suminf.    0.01432 (2) obj. -41.0501 iterations 0
Cbc0038I Pass  15: suminf.    0.01432 (2) obj. -41.0501 iterations 0
Cbc0038I Pass  16: suminf.    0.01432 (2) obj. -41.0501 iterations 0
Cbc0038I Pass  17: suminf.    0.01432 (2) obj. -41.0501 iterations 0
Cbc0038I Pass  18: suminf.    0.01432 (2) obj. -41.0501 iterations 0
Cbc0038I Pass  19: suminf.    0.12000 (2) obj. -41.0505 iterations 1
Cbc0038I Pass  20: suminf.    0.12000 (2) obj. -41.0505 iterations 0
Cbc0038I Pass  21: suminf.    0.12000 (2) obj. -41.0505 iterations 0
Cbc0038I Pass  22: suminf.    0.12000 (2) obj. -41.0505 iterations 0
Cbc0038I Pass  23: suminf.    0.01432 (2) obj. -41.0501 iterations 1
Cbc0038I Pass  24: suminf.    0.01432 (2) obj. -41.0501 iterations 0
Cbc0038I Pass  25: suminf.    0.01432 (2) obj. -41.0501 iterations 0
Cbc0038I Pass  26: suminf.    0.12000 (2) obj. -41.0505 iterations 1
Cbc0038I Pass  27: suminf.    0.01432 (2) obj. -41.0501 iterations 1
Cbc0038I Pass  28: suminf.    0.01432 (2) obj. -41.0501 iterations 0
Cbc0038I Pass  29: suminf.    0.01432 (2) obj. -41.0501 iterations 0
Cbc0038I Pass  30: suminf.    0.01432 (2) obj. -41.0501 iterations 0
Cbc0038I No solution found this major pass
Cbc0038I Before mini branch and bound, 309 integers at bound fixed and 0 continuous
Cbc0038I Mini branch and bound did not improve solution (0.01 seconds)
Cbc0038I After 0.01 seconds - Feasibility pump exiting with objective of -41.05 - took 0.00 seconds
Cbc0012I Integer solution of -41.050027 found by feasibility pump after 0 iterations and 0 nodes (0.01 seconds)
Cbc0001I Search completed - best objective -41.050026655199, took 0 iterations and 0 nodes (0.01 seconds)
Cbc0035I Maximum depth 0, 305 variables fixed on reduced cost
Cuts at root node changed objective from -41.0505 to -41.05
Probing was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Gomory was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Knapsack was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)

In [38]:
total_score.item()

2356.0

In [39]:
scores

                                                 team  gw_score
0   [adam_armstrong, cameron_archer, daniel_castel...      36.0
1   [antoine_semenyo, bukayo_saka, danny_welbeck, ...      62.0
2   [andrew_robertson, bukayo_saka, cole_palmer, c...      66.0
3   [andrew_robertson, bukayo_saka, cole_palmer, d...      31.0
4   [andrew_robertson, arijanet_muric, bukayo_saka...      82.0
5   [andre_onana, andrew_robertson, dwight_mcneil,...      66.0
6   [bukayo_saka, cole_palmer, dwight_mcneil, erli...      65.0
7   [ashley_young, cole_palmer, dwight_mcneil, erl...      56.0
8   [bukayo_saka, cole_palmer, david_raya_martin, ...      66.0
9   [bryan_mbeumo, bukayo_saka, cole_palmer, david...      48.0
10  [bukayo_saka, danny_welbeck, david_raya_martin...      46.0
11  [bryan_mbeumo, bukayo_saka, diego_carlos_santo...      63.0
12  [alex_iwobi, bukayo_saka, caoimhin_kelleher, c...      91.0
13  [alex_iwobi, bernd_leno, bukayo_saka, daniel_m...      81.0
14  [andrew_robertson, bart_verbruggen, bukayo_sak...      62.0
15  [alexander_isak, bart_verbruggen, bukayo_saka,...      55.0
16  [alex_iwobi, alexander_isak, andre_onana, buka...      83.0
17  [alexander_isak, bruno_borges_fernandes, cole_...      57.0
18  [alexander_isak, andre_onana, anthony_gordon, ...      89.0
19  [alexander_isak, alisson_ramses_becker, anthon...      60.0
20  [alexander_isak, anthony_gordon, bruno_borges_...      71.0
21  [alexander_isak, alisson_ramses_becker, anthon...      64.0
22  [alexander_isak, alisson_ramses_becker, anthon...      77.0
23  [alexander_isak, anthony_gordon, cole_palmer, ...      68.0
24  [alexander_isak, alisson_ramses_becker, antoin...      52.0
25  [alexander_isak, anthony_gordon, chris_wood, c...      71.0
26  [alisson_ramses_becker, bruno_borges_fernandes...      73.0
27  [alexander_isak, dango_ouattara, erling_haalan...      57.0
28  [alexander_isak, alisson_ramses_becker, anthon...      57.0
29  [alexander_isak, bruno_borges_fernandes, bukay...      54.0
30  [alexander_isak, bryan_mbeumo, bukayo_saka, ca...      39.0
31  [alexander_isak, alisson_ramses_becker, bruno_...      43.0
32  [alexander_isak, alisson_ramses_becker, bruno_...      89.0
33  [alexander_isak, alisson_ramses_becker, bruno_...      73.0
34  [alexander_isak, alisson_ramses_becker, bryan_...      52.0
35  [adam_webster, alexander_isak, alisson_ramses_...      48.0
36  [adam_webster, bruno_borges_fernandes, bukayo_...      41.0
37  [alexander_isak, alisson_ramses_becker, bruno_...      62.0