In [1]:
import os
import torch
import pandas as pd
import numpy as np
import pickle
from eval import season_performance_with_unlimited_transfers
import json
from model import FPLSequenceModel

In [2]:
base_path = os.getcwd()
base_path

'/Users/bragehs/Documents/FPL_forecast/predictor'

In [3]:
data_path = os.path.join(base_path, 'processed_data')
data_path

'/Users/bragehs/Documents/FPL_forecast/predictor/processed_data'

In [4]:
X_test_numeric = torch.load(data_path + '/X_test.pt', weights_only=True)
X_test_static = torch.load(data_path + '/X_static_test.pt', weights_only=True)
y_test = torch.load(data_path + '/y_test.pt', weights_only=True)
test_mapping = pd.read_csv(data_path + '/test_mapping.csv')
player_ids_test = torch.load(data_path + '/test_player_ids.pt', weights_only=True)
pos_ids_test = torch.load(data_path + '/pos_test.pt', weights_only=True)
fixdiff_ids_test = torch.load(data_path + '/fixdiff_test.pt', weights_only=True)

In [5]:
best_model_data = torch.load("best_model_mae.pth", map_location=torch.device('cpu'))

/var/folders/yv/683h12gj4mdc5txzm0lh6j0h0000gn/T/ipykernel_35937/2216842584.py:1: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  best_model_data = torch.load("best_model_mae.pth", map_location=torch.device('cpu'))

In [6]:
print(best_model_data.keys())
for k, v in best_model_data['model_state_dict'].items():
    if 'embedding' in k:
        print(k, v.shape)

dict_keys(['model_state_dict', 'best_performance', 'hidden_dim', 'lstm_layers', 'dropout'])
position_embedding.weight torch.Size([6, 16])
fixdiff_embedding.weight torch.Size([6, 16])

In [7]:
with open(f"{data_path}/vocab/player_name_to_idx.json") as f:
    name_to_idx = json.load(f)
with open(f"{data_path}/vocab/unk_id.txt") as f:
    unk_id = int(f.read())

In [8]:
print(best_model_data['hidden_dim'])
print(best_model_data['lstm_layers'])

192
2

In [9]:
model = FPLSequenceModel(
            numeric_seq_dim=X_test_numeric.shape[-1],
            static_dim=X_test_static.shape[-1],
            hidden_dim=best_model_data['hidden_dim'],
            lstm_layers=best_model_data["lstm_layers"],
            dropout=0.0,
            position_vocab_size=6,
            position_embed_dim=16,
            fixture_diff_vocab_size=6,
            fixture_diff_embed_dim=16,
        )
model.load_state_dict(best_model_data['model_state_dict'])

In [10]:
#print number of parameters in the model
num_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
print(f"Number of parameters in the model: {num_params}")

Number of parameters in the model: 608578

In [11]:
model.eval()

FPLSequenceModel(
  (position_embedding): Embedding(6, 16, padding_idx=0)
  (fixdiff_embedding): Embedding(6, 16, padding_idx=0)
  (embedding_dropout): Dropout(p=0.1, inplace=False)
  (locked_dropout_in): LockedDropout()
  (lstm): LSTM(48, 192, num_layers=2, batch_first=True)
  (locked_dropout_out): LockedDropout()
  (attn_pool): AttentionPool(
    (proj): Sequential(
      (0): Linear(in_features=192, out_features=64, bias=True)
      (1): ReLU()
      (2): Linear(in_features=64, out_features=1, bias=True)
    )
  )
  (out_dropout): Dropout(p=0.0, inplace=False)
  (head_points): Sequential(
    (0): Linear(in_features=590, out_features=192, bias=True)
    (1): ReLU()
    (2): Dropout(p=0.2, inplace=False)
    (3): Linear(in_features=192, out_features=1, bias=True)
  )
)

In [12]:
test = pd.read_csv(data_path + '/test_data.csv')

In [13]:
test.columns

Index(['GW', 'last_1_assists', 'last_3_assists', 'last_5_assists',
       'last_1_bonus', 'last_3_bonus', 'last_5_bonus', 'last_1_creativity',
       'last_3_creativity', 'last_5_creativity', 'last_1_clean_sheets',
       'last_3_clean_sheets', 'last_5_clean_sheets', 'last_1_goals_conceded',
       'last_3_goals_conceded', 'last_5_goals_conceded', 'last_1_goals_scored',
       'last_3_goals_scored', 'last_5_goals_scored', 'last_1_ict_index',
       'last_3_ict_index', 'last_5_ict_index', 'last_1_influence',
       'last_3_influence', 'last_5_influence', 'last_1_minutes',
       'last_3_minutes', 'last_5_minutes', 'last_1_threat', 'last_3_threat',
       'last_5_threat', 'last_1_red_cards', 'last_3_red_cards',
       'last_5_red_cards', 'last_1_yellow_cards', 'last_3_yellow_cards',
       'last_5_yellow_cards', 'last_1_team_score', 'last_3_team_score',
       'last_5_team_score', 'last_1_opponent_score', 'last_3_opponent_score',
       'last_5_opponent_score', 'last_all_assists', 'last_all_bonus',
       'last_all_creativity', 'last_all_clean_sheets',
       'last_all_goals_conceded', 'last_all_goals_scored',
       'last_all_ict_index', 'last_all_influence', 'last_all_minutes',
       'last_all_threat', 'last_all_red_cards', 'last_all_yellow_cards',
       'last_all_team_score', 'last_all_opponent_score', 'lagged_was_home',
       'season_progress', 'season_x', 'value', 'team_x', 'name', 'element',
       'minutes', 'position_encoded', 'lagged_fixture_difficulty', 'was_home',
       'season_progress.1', 'total_points'],
      dtype='object')

In [15]:
def forward_model(x_numeric, x_static, pos=None, fixd=None):
    kwargs = {}
    if getattr(model, 'use_position', False) and pos is not None:
        kwargs['pos_ids'] = pos
    if getattr(model, 'use_fixdiff', False) and fixd is not None:
        kwargs['fixdiff_ids'] = fixd
    try:
        return model(x_numeric, x_static, **kwargs) if kwargs else model(x_numeric, x_static)
    except TypeError:
        return model(x_numeric, x_static)

In [16]:
predictions = forward_model(X_test_numeric, X_test_static , pos=pos_ids_test, fixd=fixdiff_ids_test).detach().numpy()
print(predictions.shape)
print(y_test.shape)

(27283, 1)
torch.Size([27283, 1])

In [17]:
def make_predicted_table(y_test, y_pred):
    '''
    Create a DataFrame for LSTM model predictions.
    This needs to keep track of the Gameweek (GW) and player names.
    '''
    test_mapping = pd.read_csv(data_path + '/test_mapping.csv')
    predictions_df = test_mapping.copy()
    predictions_df['actual'] = y_test
    predictions_df['predicted'] = y_pred
    predictions_df['predicted'] = predictions_df['predicted'].where(predictions_df['minutes'] > 0, 0)
    predictions_df.rename(columns={'prediction_gw': 'GW'}, inplace=True)


    # Update the predictions_df reference
    predictions_df = predictions_df.drop_duplicates(subset=['name', 'GW'], keep='last')
    
    return predictions_df

In [18]:
df = make_predicted_table(y_test, predictions)

In [19]:
salah = df[df['name'] == 'mohamed_salah']
salah

,sequence_idx,element,season_x,name,GW,team_x,value,minutes,last_1_goals_scored,last_1_assists,padding_used,position_encoded,actual,predicted
12426,12426,328.0,2024-25,mohamed_salah,1.0,NaN,125.0,90.0,0.00,0.00,4,3.0,14.0,0.656353
12427,12427,328.0,2024-25,mohamed_salah,2.0,NaN,125.0,82.0,0.25,0.25,3,3.0,10.0,2.656297
12428,12428,328.0,2024-25,mohamed_salah,3.0,NaN,126.0,90.0,0.25,0.00,2,3.0,17.0,2.721791
12429,12429,328.0,2024-25,mohamed_salah,4.0,NaN,127.0,90.0,0.25,0.50,1,3.0,2.0,3.021735
12430,12430,328.0,2024-25,mohamed_salah,5.0,NaN,127.0,90.0,0.00,0.00,0,3.0,6.0,2.505668
12431,12431,328.0,2024-25,mohamed_salah,6.0,NaN,128.0,90.0,0.00,0.25,0,3.0,10.0,3.051100
12432,12432,328.0,2024-25,mohamed_salah,7.0,NaN,127.0,72.0,0.25,0.00,0,3.0,3.0,3.087439
12433,12433,328.0,2024-25,mohamed_salah,8.0,NaN,126.0,90.0,0.00,0.00,0,3.0,12.0,2.711574
12434,12434,328.0,2024-25,mohamed_salah,9.0,NaN,126.0,90.0,0.25,0.25,0,3.0,10.0,2.778683
12435,12435,328.0,2024-25,mohamed_salah,10.0,NaN,127.0,90.0,0.25,0.00,0,3.0,9.0,3.062077
12436,12436,328.0,2024-25,mohamed_salah,11.0,NaN,128.0,90.0,0.25,0.00,0,3.0,14.0,3.094861
12437,12437,328.0,2024-25,mohamed_salah,12.0,NaN,130.0,90.0,0.25,0.25,0,3.0,13.0,3.234113
12438,12438,328.0,2024-25,mohamed_salah,13.0,NaN,131.0,83.0,0.50,0.00,0,3.0,13.0,3.385074
12439,12439,328.0,2024-25,mohamed_salah,14.0,NaN,132.0,90.0,0.25,0.25,0,3.0,18.0,3.371267
12440,12440,328.0,2024-25,mohamed_salah,15.0,NaN,137.0,90.0,0.50,0.25,0,3.0,13.0,3.871437
12441,12441,328.0,2024-25,mohamed_salah,16.0,NaN,134.0,90.0,0.25,0.25,0,3.0,5.0,3.667727
12442,12442,328.0,2024-25,mohamed_salah,17.0,NaN,134.0,86.0,0.00,0.25,0,3.0,21.0,3.562079
12443,12443,328.0,2024-25,mohamed_salah,18.0,NaN,135.0,90.0,0.50,0.50,0,3.0,9.0,4.030327
12444,12444,328.0,2024-25,mohamed_salah,19.0,NaN,136.0,90.0,0.25,0.00,0,3.0,16.0,3.803733
12445,12445,328.0,2024-25,mohamed_salah,20.0,NaN,136.0,90.0,0.25,0.50,0,3.0,7.0,4.348003
12446,12446,328.0,2024-25,mohamed_salah,21.0,NaN,137.0,90.0,0.25,0.00,0,3.0,2.0,4.039084
12447,12447,328.0,2024-25,mohamed_salah,22.0,NaN,137.0,90.0,0.00,0.00,0,3.0,3.0,4.189504
12448,12448,328.0,2024-25,mohamed_salah,23.0,NaN,137.0,90.0,0.00,0.00,0,3.0,8.0,4.238834
12449,12449,328.0,2024-25,mohamed_salah,24.0,NaN,137.0,87.0,0.25,0.00,0,3.0,16.0,4.007116
12450,12450,328.0,2024-25,mohamed_salah,25.0,NaN,137.0,90.0,0.50,0.00,0,3.0,8.0,4.280932
12451,12451,328.0,2024-25,mohamed_salah,26.0,NaN,137.0,90.0,0.25,0.00,0,3.0,14.0,4.231139
12452,12452,328.0,2024-25,mohamed_salah,27.0,NaN,137.0,90.0,0.25,0.25,0,3.0,6.0,4.431907
12453,12453,328.0,2024-25,mohamed_salah,28.0,NaN,138.0,90.0,0.00,0.25,0,3.0,15.0,4.395875
12454,12454,328.0,2024-25,mohamed_salah,29.0,NaN,137.0,90.0,0.50,0.00,0,3.0,12.0,4.550612
12455,12455,328.0,2024-25,mohamed_salah,30.0,NaN,137.0,90.0,0.25,0.25,0,3.0,3.0,4.750948
12456,12456,328.0,2024-25,mohamed_salah,31.0,NaN,138.0,90.0,0.00,0.00,0,3.0,2.0,4.636038
12457,12457,328.0,2024-25,mohamed_salah,32.0,NaN,138.0,84.0,0.00,0.00,0,3.0,6.0,4.507094
12458,12458,328.0,2024-25,mohamed_salah,33.0,NaN,138.0,90.0,0.00,0.25,0,3.0,3.0,4.143189
12459,12459,328.0,2024-25,mohamed_salah,34.0,NaN,138.0,90.0,0.00,0.00,0,3.0,8.0,4.400484
12460,12460,328.0,2024-25,mohamed_salah,35.0,NaN,138.0,90.0,0.25,0.00,0,3.0,2.0,4.409577
12461,12461,328.0,2024-25,mohamed_salah,36.0,NaN,137.0,90.0,0.00,0.00,0,3.0,2.0,4.456345
12462,12462,328.0,2024-25,mohamed_salah,37.0,NaN,136.0,90.0,0.00,0.00,0,3.0,2.0,4.392481
12463,12463,328.0,2024-25,mohamed_salah,38.0,NaN,136.0,90.0,0.00,0.00,0,3.0,10.0,4.688276

In [20]:
print(torch.mean(y_test))
print(torch.var(y_test))

tensor(1.1469)
tensor(5.3394)

In [21]:
print(np.mean(predictions))
print(np.var(predictions))
print(np.max(predictions))

0.67488027
0.6571421
4.7509484

In [22]:
from sklearn.metrics import root_mean_squared_error, mean_absolute_error

rmse = root_mean_squared_error(y_test, predictions)
print(f"RMSE: {rmse}")

mae = mean_absolute_error(y_test, predictions)
print(f"MAE: {mae}")

RMSE: 2.042497158050537
MAE: 0.8875532746315002

In [23]:
X_test_numeric.shape

torch.Size([27283, 5, 16])

In [25]:
scores, total_score = season_performance_with_unlimited_transfers(
    y_test=y_test,
    predictions=predictions,
)

Players with NaN total_points_last_season: []
Number of NaN values remaining: 0
1.0 :  lukasz_fabianski
2.0 :  sepp_van_den_berg
3.0 :  tyler_dibling
4.0 :  daniel_jebbison
Bench players: ['lukasz_fabianski', 'sepp_van_den_berg', 'tyler_dibling', 'daniel_jebbison']
Bench cost: 170.0
Simulating season with unlimited transfers for 38 gameweeks
Available budget per gameweek: 830.0

--- Gameweek 1.0 ---
Players available for GW 1.0: 668
Welcome to the CBC MILP Solver
Version: 2.10.3
Build Date: Dec 15 2019

command line - /opt/anaconda3/envs/fpl_helper/lib/python3.11/site-packages/pulp/apis/../solverdir/cbc/osx/i64/cbc /var/folders/yv/683h12gj4mdc5txzm0lh6j0h0000gn/T/782069c8ac8749b8abba0b3449bbedb1-pulp.mps -max -timeMode elapsed -branch -printingOptions all -solution /var/folders/yv/683h12gj4mdc5txzm0lh6j0h0000gn/T/782069c8ac8749b8abba0b3449bbedb1-pulp.sol (default strategy 1)
At line 2 NAME          MODEL
At line 3 ROWS
At line 30 COLUMNS
At line 3687 RHS
At line 3713 BOUNDS
At line 4382 ENDATA
Problem MODEL has 25 rows, 668 columns and 2004 elements
Coin0008I MODEL read with 0 errors
Option for timeMode changed from cpu to elapsed
Continuous objective value is 6.34257 - 0.00 seconds
Cgl0003I 0 fixed, 7 tightened bounds, 0 strengthened rows, 0 substitutions
Cgl0003I 0 fixed, 1 tightened bounds, 0 strengthened rows, 0 substitutions
Cgl0004I processed model has 25 rows, 317 columns (317 integer (198 of which binary)) and 951 elements
Cbc0038I Initial state - 0 integers unsatisfied sum - 0
Cbc0038I Solution found of -6.34257
Cbc0038I Cleaned solution of -6.34257
Cbc0038I Before mini branch and bound, 317 integers at bound fixed and 0 continuous of which 1 were internal integer and 0 internal continuous
Cbc0038I Mini branch and bound did not improve solution (0.02 seconds)
Cbc0038I After 0.02 seconds - Feasibility pump exiting with objective of -6.34257 - took 0.00 seconds
Cbc0012I Integer solution of -6.3425661 found by feasibility pump after 0 iterations and 0 nodes (0.02 seconds)
Cbc0001I Search completed - best objective -6.342566102743301, took 0 iterations and 0 nodes (0.02 seconds)
Cbc0035I Maximum depth 0, 0 variables fixed on reduced cost
Cuts at root node changed objective from -6.34257 to -6.34257
Probing was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Gomory was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Knapsack was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Clique was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
MixedIntegerRounding2 was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
FlowCover was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
TwoMirCuts was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
ZeroHalf was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)

Result - Optimal solution found

Objective value:                6.34256610
Enumerated nodes:               0
Total iterations:               0
Time (CPU seconds):             0.01
Time (Wallclock seconds):       0.02

Option for printingOptions changed from normal to all
Total time (CPU seconds):       0.01   (Wallclock seconds):       0.03

                     name  actual  predicted
11020           wout_faes     1.0   0.527834
11590         jamie_vardy     8.0   0.622041
11628  jannik_vestergaard     2.0   0.527834
15200      alexander_isak     5.0   0.622041
15656           nick_pope     9.0   0.338243
15732        fabian_schar    -2.0   0.527834
18659    dejan_kulusevski     1.0   0.656353
18735      james_maddison     5.0   0.656353
23705      ilkay_gundogan     1.0   0.668100
24607     maxence_lacroix     1.0   0.527834
26824       marco_asensio     1.0   0.668100
total_score for gameweek 1.0 : 33.0
GW 1.0 optimal team: ['alexander_isak', 'dejan_kulusevski', 'fabian_schar', 'ilkay_gundogan', 'james_maddison', 'jamie_vardy', 'jannik_vestergaard', 'marco_asensio', 'maxence_lacroix', 'nick_pope', 'wout_faes']
GW 1.0 score: 33.0
Team cost: 635.0

--- Gameweek 2.0 ---
Players available for GW 2.0: 675
Welcome to the CBC MILP Solver
Version: 2.10.3
Build Date: Dec 15 2019

command line - /opt/anaconda3/envs/fpl_helper/lib/python3.11/site-packages/pulp/apis/../solverdir/cbc/osx/i64/cbc /var/folders/yv/683h12gj4mdc5txzm0lh6j0h0000gn/T/a2cb5329fb514eca98e43cf8bf381046-pulp.mps -max -timeMode elapsed -branch -printingOptions all -solution /var/folders/yv/683h12gj4mdc5txzm0lh6j0h0000gn/T/a2cb5329fb514eca98e43cf8bf381046-pulp.sol (default strategy 1)
At line 2 NAME          MODEL
At line 3 ROWS
At line 30 COLUMNS
At line 3725 RHS
At line 3751 BOUNDS
At line 4427 ENDATA
Problem MODEL has 25 rows, 675 columns and 2025 elements
Coin0008I MODEL read with 0 errors
Option for timeMode changed from cpu to elapsed
Continuous objective value is 24.5722 - 0.00 seconds
Cgl0003I 0 fixed, 5 tightened bounds, 0 strengthened rows, 0 substitutions
Cgl0003I 0 fixed, 3 tightened bounds, 0 strengthened rows, 0 substitutions
Cgl0004I processed model has 25 rows, 485 columns (485 integer (410 of which binary)) and 1455 elements
Cbc0038I Initial state - 0 integers unsatisfied sum - 0
Cbc0038I Solution found of -24.5722
Cbc0038I Cleaned solution of -24.5722
Cbc0038I Before mini branch and bound, 485 integers at bound fixed and 0 continuous
Cbc0038I Mini branch and bound did not improve solution (0.01 seconds)
Cbc0038I After 0.01 seconds - Feasibility pump exiting with objective of -24.5722 - took 0.00 seconds
Cbc0012I Integer solution of -24.572194 found by feasibility pump after 0 iterations and 0 nodes (0.01 seconds)
Cbc0001I Search completed - best objective -24.572193741798, took 0 iterations and 0 nodes (0.01 seconds)
Cbc0035I Maximum depth 0, 0 variables fixed on reduced cost
Cuts at root node changed objective from -24.5722 to -24.5722
Probing was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Gomory was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Knapsack was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Clique was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
MixedIntegerRounding2 was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
FlowCover was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
TwoMirCuts was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
ZeroHalf was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)

Result - Optimal solution found

Objective value:                24.57219374
Enumerated nodes:               0
Total iterations:               0
Time (CPU seconds):             0.01
Time (Wallclock seconds):       0.01

Option for printingOptions changed from normal to all
Total time (CPU seconds):       0.01   (Wallclock seconds):       0.01

                                     name  actual  predicted
115                           kai_havertz     2.0   2.393145
533                     david_raya_martin    10.0   1.991267
609                           bukayo_saka     6.0   2.822499
5131                         mitoma_kaoru     6.0   2.661310
5473                         joel_veltman     2.0   1.735089
5587                        danny_welbeck     9.0   2.375658
12427                       mohamed_salah    10.0   2.656297
12959  bernardo_veiga_de_carvalho_e_silva     2.0   2.483133
13263                      josko_gvardiol     2.0   1.793307
13453                          rico_lewis     2.0   1.761522
18774                         pedro_porro     6.0   1.898967
total_score for gameweek 2.0 : 63.0
GW 2.0 optimal team: ['bernardo_veiga_de_carvalho_e_silva', 'bukayo_saka', 'danny_welbeck', 'david_raya_martin', 'joel_veltman', 'josko_gvardiol', 'kai_havertz', 'mitoma_kaoru', 'mohamed_salah', 'pedro_porro', 'rico_lewis']
GW 2.0 score: 63.0
Team cost: 750.0

--- Gameweek 3.0 ---
Players available for GW 3.0: 686
Welcome to the CBC MILP Solver
Version: 2.10.3
Build Date: Dec 15 2019

command line - /opt/anaconda3/envs/fpl_helper/lib/python3.11/site-packages/pulp/apis/../solverdir/cbc/osx/i64/cbc /var/folders/yv/683h12gj4mdc5txzm0lh6j0h0000gn/T/c6792effebe6484c8aacd0062ef3a8b3-pulp.mps -max -timeMode elapsed -branch -printingOptions all -solution /var/folders/yv/683h12gj4mdc5txzm0lh6j0h0000gn/T/c6792effebe6484c8aacd0062ef3a8b3-pulp.sol (default strategy 1)
At line 2 NAME          MODEL
At line 3 ROWS
At line 30 COLUMNS
At line 3773 RHS
At line 3799 BOUNDS
At line 4486 ENDATA
Problem MODEL has 25 rows, 686 columns and 2058 elements
Coin0008I MODEL read with 0 errors
Option for timeMode changed from cpu to elapsed
Continuous objective value is 25.4921 - 0.00 seconds
Cgl0003I 0 fixed, 7 tightened bounds, 0 strengthened rows, 0 substitutions
Cgl0003I 0 fixed, 4 tightened bounds, 0 strengthened rows, 0 substitutions
Cgl0004I processed model has 25 rows, 478 columns (478 integer (397 of which binary)) and 1434 elements
Cbc0038I Initial state - 2 integers unsatisfied sum - 1
Cbc0038I Pass   1: suminf.    0.19048 (2) obj. -25.2329 iterations 5
Cbc0038I Pass   2: suminf.    0.00000 (0) obj. -22.6953 iterations 2
Cbc0038I Solution found of -22.6953
Cbc0038I Cleaned solution of -22.6953
Cbc0038I Before mini branch and bound, 474 integers at bound fixed and 0 continuous
Cbc0038I Full problem 25 rows 478 columns, reduced to 1 rows 2 columns
Cbc0038I Mini branch and bound improved solution from -22.6953 to -25.4841 (0.01 seconds)
Cbc0038I Round again with cutoff of -25.4849
Cbc0038I Reduced cost fixing fixed 473 variables on major pass 2
Cbc0038I Pass   3: suminf.    1.00000 (2) obj. -25.4921 iterations 4
Cbc0038I Pass   4: suminf.    0.10113 (2) obj. -25.4849 iterations 4
Cbc0038I Pass   5: suminf.    0.10113 (2) obj. -25.4849 iterations 0
Cbc0038I Pass   6: suminf.    0.10113 (2) obj. -25.4849 iterations 0
Cbc0038I Pass   7: suminf.    0.10113 (2) obj. -25.4849 iterations 0
Cbc0038I Pass   8: suminf.    0.10113 (2) obj. -25.4849 iterations 0
Cbc0038I Pass   9: suminf.    0.10113 (2) obj. -25.4849 iterations 0
Cbc0038I Pass  10: suminf.    0.10113 (2) obj. -25.4849 iterations 0
Cbc0038I Pass  11: suminf.    0.10113 (2) obj. -25.4849 iterations 0
Cbc0038I Pass  12: suminf.    0.10113 (2) obj. -25.4849 iterations 0
Cbc0038I Pass  13: suminf.    0.10113 (2) obj. -25.4849 iterations 0
Cbc0038I Pass  14: suminf.    0.10113 (2) obj. -25.4849 iterations 0
Cbc0038I Pass  15: suminf.    0.10113 (2) obj. -25.4849 iterations 0
Cbc0038I Pass  16: suminf.    0.10113 (2) obj. -25.4849 iterations 0
Cbc0038I Pass  17: suminf.    0.10113 (2) obj. -25.4849 iterations 0
Cbc0038I Pass  18: suminf.    1.00000 (2) obj. -25.4921 iterations 1
Cbc0038I Pass  19: suminf.    0.10113 (2) obj. -25.4849 iterations 1
Cbc0038I Pass  20: suminf.    0.10113 (2) obj. -25.4849 iterations 0
Cbc0038I Pass  21: suminf.    0.10113 (2) obj. -25.4849 iterations 0
Cbc0038I Pass  22: suminf.    0.10113 (2) obj. -25.4849 iterations 0
Cbc0038I Pass  23: suminf.    1.00000 (2) obj. -25.4921 iterations 1
Cbc0038I Pass  24: suminf.    1.00000 (2) obj. -25.4921 iterations 0
Cbc0038I Pass  25: suminf.    1.00000 (2) obj. -25.4921 iterations 0
Cbc0038I Pass  26: suminf.    1.00000 (2) obj. -25.4921 iterations 0
Cbc0038I Pass  27: suminf.    1.00000 (2) obj. -25.4921 iterations 0
Cbc0038I Pass  28: suminf.    1.00000 (2) obj. -25.4921 iterations 0
Cbc0038I Pass  29: suminf.    1.00000 (2) obj. -25.4921 iterations 0
Cbc0038I Pass  30: suminf.    0.10113 (2) obj. -25.4849 iterations 1
Cbc0038I Pass  31: suminf.    1.00000 (2) obj. -25.4921 iterations 1
Cbc0038I Pass  32: suminf.    1.00000 (2) obj. -25.4921 iterations 0
Cbc0038I No solution found this major pass
Cbc0038I Before mini branch and bound, 476 integers at bound fixed and 0 continuous
Cbc0038I Mini branch and bound did not improve solution (0.02 seconds)
Cbc0038I After 0.02 seconds - Feasibility pump exiting with objective of -25.4841 - took 0.01 seconds
Cbc0012I Integer solution of -25.484117 found by feasibility pump after 0 iterations and 0 nodes (0.02 seconds)
Cbc0012I Integer solution of -25.484158 found by DiveCoefficient after 0 iterations and 0 nodes (0.02 seconds)
Cbc0013I At root node, 0 cuts changed objective from -25.492078 to -25.484158 in 2 passes
Cbc0014I Cut generator 0 (Probing) - 3 row cuts average 2.3 elements, 1 column cuts (1 active)  in 0.000 seconds - new frequency is 1
Cbc0014I Cut generator 1 (Gomory) - 0 row cuts average 0.0 elements, 0 column cuts (0 active)  in 0.000 seconds - new frequency is -100
Cbc0014I Cut generator 2 (Knapsack) - 0 row cuts average 0.0 elements, 0 column cuts (0 active)  in 0.000 seconds - new frequency is -100
Cbc0014I Cut generator 3 (Clique) - 0 row cuts average 0.0 elements, 0 column cuts (0 active)  in 0.000 seconds - new frequency is -100
Cbc0014I Cut generator 4 (MixedIntegerRounding2) - 0 row cuts average 0.0 elements, 0 column cuts (0 active)  in 0.000 seconds - new frequency is -100
Cbc0014I Cut generator 5 (FlowCover) - 0 row cuts average 0.0 elements, 0 column cuts (0 active)  in 0.000 seconds - new frequency is -100
Cbc0001I Search completed - best objective -25.48415768146599, took 0 iterations and 0 nodes (0.02 seconds)
Cbc0035I Maximum depth 0, 391 variables fixed on reduced cost
Cuts at root node changed objective from -25.4921 to -25.4842
Probing was tried 2 times and created 4 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Gomory was tried 2 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Knapsack was tried 2 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Clique was tried 2 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
MixedIntegerRounding2 was tried 2 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
FlowCover was tried 2 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
TwoMirCuts was tried 1 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
ZeroHalf was tried 1 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)

Result - Optimal solution found

Objective value:                25.48415768
Enumerated nodes:               0
Total iterations:               0
Time (CPU seconds):             0.02
Time (Wallclock seconds):       0.02

Option for printingOptions changed from normal to all
Total time (CPU seconds):       0.02   (Wallclock seconds):       0.02

                          name  actual  predicted
534          david_raya_martin     2.0   2.517887
610                bukayo_saka     6.0   2.783895
3118          marcus_tavernier     2.0   2.513205
6804           nicolas_jackson     6.0   2.209391
12390                luis_diaz    15.0   2.529127
12428            mohamed_salah    17.0   2.721791
13302           erling_haaland    17.0   2.804724
18775              pedro_porro     1.0   1.787867
18889          cristian_romero     1.0   1.851194
19877               max_kilman     0.0   1.967934
20029  konstantinos_mavropanos     1.0   1.797142
total_score for gameweek 3.0 : 85.0
GW 3.0 optimal team: ['bukayo_saka', 'cristian_romero', 'david_raya_martin', 'erling_haaland', 'konstantinos_mavropanos', 'luis_diaz', 'marcus_tavernier', 'max_kilman', 'mohamed_salah', 'nicolas_jackson', 'pedro_porro']
GW 3.0 score: 85.0
Team cost: 830.0

--- Gameweek 4.0 ---
Players available for GW 4.0: 692
Welcome to the CBC MILP Solver
Version: 2.10.3
Build Date: Dec 15 2019

command line - /opt/anaconda3/envs/fpl_helper/lib/python3.11/site-packages/pulp/apis/../solverdir/cbc/osx/i64/cbc /var/folders/yv/683h12gj4mdc5txzm0lh6j0h0000gn/T/71707410ab9e46efad903957ab1cb822-pulp.mps -max -timeMode elapsed -branch -printingOptions all -solution /var/folders/yv/683h12gj4mdc5txzm0lh6j0h0000gn/T/71707410ab9e46efad903957ab1cb822-pulp.sol (default strategy 1)
At line 2 NAME          MODEL
At line 3 ROWS
At line 30 COLUMNS
At line 3806 RHS
At line 3832 BOUNDS
At line 4525 ENDATA
Problem MODEL has 25 rows, 692 columns and 2076 elements
Coin0008I MODEL read with 0 errors
Option for timeMode changed from cpu to elapsed
Continuous objective value is 26.0232 - 0.00 seconds
Cgl0003I 0 fixed, 9 tightened bounds, 0 strengthened rows, 0 substitutions
Cgl0003I 0 fixed, 4 tightened bounds, 0 strengthened rows, 0 substitutions
Cgl0004I processed model has 25 rows, 487 columns (487 integer (407 of which binary)) and 1461 elements
Cbc0038I Initial state - 0 integers unsatisfied sum - 0
Cbc0038I Solution found of -26.0232
Cbc0038I Cleaned solution of -26.0232
Cbc0038I Before mini branch and bound, 487 integers at bound fixed and 0 continuous
Cbc0038I Mini branch and bound did not improve solution (0.01 seconds)
Cbc0038I After 0.01 seconds - Feasibility pump exiting with objective of -26.0232 - took 0.00 seconds
Cbc0012I Integer solution of -26.023162 found by feasibility pump after 0 iterations and 0 nodes (0.01 seconds)
Cbc0001I Search completed - best objective -26.023161649705, took 0 iterations and 0 nodes (0.01 seconds)
Cbc0035I Maximum depth 0, 0 variables fixed on reduced cost
Cuts at root node changed objective from -26.0232 to -26.0232
Probing was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Gomory was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Knapsack was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Clique was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
MixedIntegerRounding2 was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
FlowCover was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
TwoMirCuts was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
ZeroHalf was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)

Result - Optimal solution found

Objective value:                26.02316165
Enumerated nodes:               0
Total iterations:               0
Time (CPU seconds):             0.01
Time (Wallclock seconds):       0.01

Option for printingOptions changed from normal to all
Total time (CPU seconds):       0.01   (Wallclock seconds):       0.01

                        name  actual  predicted
611              bukayo_saka     7.0   2.593835
3119        marcus_tavernier     3.0   2.642503
4525              lewis_dunk     6.0   1.832351
10111             leif_davis     6.0   1.905446
11745  alisson_ramses_becker     2.0   2.508397
12391              luis_diaz     3.0   2.773711
12429          mohamed_salah     2.0   3.021735
13303         erling_haaland    13.0   2.922717
13455             rico_lewis     1.0   1.714857
18776            pedro_porro     2.0   1.744488
26720          omar_marmoush     2.0   2.363122
total_score for gameweek 4.0 : 49.0
GW 4.0 optimal team: ['alisson_ramses_becker', 'bukayo_saka', 'erling_haaland', 'leif_davis', 'lewis_dunk', 'luis_diaz', 'marcus_tavernier', 'mohamed_salah', 'omar_marmoush', 'pedro_porro', 'rico_lewis']
GW 4.0 score: 49.0
Team cost: 820.0

--- Gameweek 5.0 ---
Players available for GW 5.0: 693

In [26]:
total_score.item()

2245.0

In [27]:
scores

                                                 team  gw_score
0   [alexander_isak, dejan_kulusevski, fabian_scha...      33.0
1   [bernardo_veiga_de_carvalho_e_silva, bukayo_sa...      63.0
2   [bukayo_saka, cristian_romero, david_raya_mart...      85.0
3   [alisson_ramses_becker, bukayo_saka, erling_ha...      49.0
4   [amad_diallo, axel_tuanzebe, bukayo_saka, dwig...      46.0
5   [andre_onana, bryan_mbeumo, danny_welbeck, dio...      36.0
6   [cole_palmer, cristian_romero, dejan_kulusevsk...      40.0
7   [brennan_johnson, bryan_mbeumo, chris_wood, co...      47.0
8   [chris_wood, cole_palmer, dwight_mcneil, erlin...      68.0
9   [alex_iwobi, bukayo_saka, chris_wood, cole_pal...      55.0
10  [aaron_ramsdale, bruno_borges_fernandes, bukay...      63.0
11  [alex_iwobi, alexander_isak, andre_onana, anth...      54.0
12  [aaron_wan_bissaka, ashley_young, bukayo_saka,...      72.0
13  [bukayo_saka, caoimhin_kelleher, chris_wood, c...      64.0
14  [alex_iwobi, alexander_isak, andre_onana, ashl...      71.0
15  [alexander_isak, andre_onana, bruno_borges_fer...      57.0
16  [alexander_isak, andre_onana, antonee_robinson...      93.0
17  [alexander_isak, antonee_robinson, bruno_borge...      68.0
18  [alexander_isak, andre_onana, anthony_gordon, ...      87.0
19  [alexander_isak, andre_onana, anthony_gordon, ...      70.0
20  [alexander_isak, andre_onana, bruno_borges_fer...      58.0
21  [alexander_isak, andre_onana, bruno_borges_fer...      55.0
22  [alexander_isak, alisson_ramses_becker, antone...      66.0
23  [alexander_isak, andre_onana, bruno_borges_fer...      56.0
24  [alisson_ramses_becker, bruno_borges_fernandes...      62.0
25  [alexander_isak, bruno_borges_fernandes, bryan...      80.0
26  [aaron_wan_bissaka, alisson_ramses_becker, bru...      64.0
27  [aaron_wan_bissaka, alisson_ramses_becker, bru...      61.0
28  [bruno_borges_fernandes, bryan_mbeumo, chris_w...      71.0
29  [alexander_isak, andre_onana, bruno_borges_fer...      42.0
30  [aaron_wan_bissaka, alexander_isak, andre_onan...      38.0
31  [alexander_isak, bruno_borges_fernandes, bryan...      61.0
32  [alexander_isak, bruno_borges_fernandes, bryan...      56.0
33  [alexander_isak, bryan_mbeumo, chris_wood, col...      53.0
34  [alexander_isak, bryan_mbeumo, cole_palmer, da...      62.0
35  [alexander_isak, bryan_mbeumo, cole_palmer, da...      45.0
36  [aaron_wan_bissaka, bryan_mbeumo, chris_wood, ...      37.0
37  [alisson_ramses_becker, bruno_borges_fernandes...      57.0