In [1]:
import os
import torch
import pandas as pd
import numpy as np
import pickle
from eval import season_performance_with_unlimited_transfers
import json
from model import FPLSequenceModel

In [2]:
base_path = os.getcwd()
base_path

'/Users/bragehs/Documents/FPL_forecast/predictor'

In [3]:
data_path = os.path.join(base_path, 'processed_data')
data_path

'/Users/bragehs/Documents/FPL_forecast/predictor/processed_data'

In [5]:
X_test_numeric = torch.load(data_path + '/X_test.pt', weights_only=True)
X_test_static = torch.load(data_path + '/X_static_test.pt', weights_only=True)
y_test = torch.load(data_path + '/y_test.pt', weights_only=True)
test_mapping = pd.read_csv(data_path + '/test_mapping.csv')

In [6]:
best_model_data = torch.load("best_model_with_mins.pth", map_location=torch.device('cpu'))

/var/folders/yv/683h12gj4mdc5txzm0lh6j0h0000gn/T/ipykernel_2816/2699782564.py:1: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  best_model_data = torch.load("best_model_with_mins.pth", map_location=torch.device('cpu'))

In [7]:
print(best_model_data.keys())
for k, v in best_model_data['model_state_dict'].items():
    if 'embedding' in k:
        print(k, v.shape)

dict_keys(['model_state_dict', 'best_performance', 'hidden_dim', 'lstm_layers', 'dropout'])

In [9]:
print(best_model_data['hidden_dim'])
print(best_model_data['lstm_layers'])

128
2

In [12]:
model = FPLSequenceModel(
            numeric_seq_dim=X_test_numeric.shape[-1],
            static_dim=X_test_static.shape[-1],
            hidden_dim=best_model_data['hidden_dim'],
            lstm_layers=best_model_data["lstm_layers"],
            dropout=0.0,
            multitask=True
        )
model.load_state_dict(best_model_data['model_state_dict'])

In [13]:
#print number of parameters in the model
num_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
print(f"Number of parameters in the model: {num_params}")

Number of parameters in the model: 267414

In [14]:
model.eval()

FPLSequenceModel(
  (embedding_dropout): Dropout(p=0.1, inplace=False)
  (locked_dropout_in): LockedDropout()
  (lstm): LSTM(16, 128, num_layers=2, batch_first=True)
  (locked_dropout_out): LockedDropout()
  (attn_pool): AttentionPool(
    (proj): Sequential(
      (0): Linear(in_features=128, out_features=64, bias=True)
      (1): ReLU()
      (2): Linear(in_features=64, out_features=1, bias=True)
    )
  )
  (out_dropout): Dropout(p=0.0, inplace=False)
  (head_points): Sequential(
    (0): Linear(in_features=403, out_features=128, bias=True)
    (1): ReLU()
    (2): Dropout(p=0.2, inplace=False)
    (3): Linear(in_features=128, out_features=1, bias=True)
  )
  (head_minutes): Linear(in_features=403, out_features=1, bias=True)
)

In [15]:
test = pd.read_csv(data_path + '/test_data.csv')

In [16]:
test.columns

Index(['GW', 'last_1_assists', 'last_1_bonus', 'last_1_creativity',
       'last_1_clean_sheets', 'last_1_goals_conceded', 'last_1_goals_scored',
       'last_1_ict_index', 'last_1_influence', 'last_1_minutes',
       'last_1_threat', 'last_1_red_cards', 'last_1_yellow_cards',
       'last_1_team_score', 'last_1_opponent_score', 'last_all_assists',
       'last_all_bonus', 'last_all_creativity', 'last_all_clean_sheets',
       'last_all_goals_conceded', 'last_all_goals_scored',
       'last_all_ict_index', 'last_all_influence', 'last_all_minutes',
       'last_all_threat', 'last_all_red_cards', 'last_all_yellow_cards',
       'last_all_team_score', 'last_all_opponent_score', 'lagged_was_home',
       'lagged_fixture_difficulty', 'position_encoded_0.0',
       'position_encoded_1.0', 'position_encoded_2.0', 'position_encoded_3.0',
       'position_encoded_4.0', 'season_x', 'value', 'team_x', 'name',
       'element', 'minutes', 'was_home', 'total_points'],
      dtype='object')

In [18]:
points_predictions, mins_predictions = model(X_test_numeric, X_test_static)
points_predictions = points_predictions.detach().numpy()
mins_predictions = mins_predictions.detach().numpy()
print(points_predictions.shape)
print(mins_predictions.shape)
print(y_test.shape)

(27283, 1)
(27283, 1)
torch.Size([27283, 1])

In [31]:
def make_predicted_table(y_test, y_pred, mins_predictions):
    '''
    Create a DataFrame for LSTM model predictions.
    This needs to keep track of the Gameweek (GW) and player names.
    '''
    test_mapping = pd.read_csv(data_path + '/test_mapping.csv')
    predictions_df = test_mapping.copy()
    predictions_df['actual'] = y_test
    predictions_df['predicted'] = y_pred
    predictions_df['minutes_pred'] = mins_predictions
    predictions_df['predicted'] = predictions_df['predicted'].where(predictions_df['minutes'] > 0, 0)
    predictions_df.rename(columns={'prediction_gw': 'GW'}, inplace=True)


    # Update the predictions_df reference
    predictions_df = predictions_df.drop_duplicates(subset=['name', 'GW'], keep='last')
    
    return predictions_df

In [32]:
df = make_predicted_table(y_test, points_predictions, mins_predictions)

In [38]:
player = df[df['name'] == 'phil_foden']
player

,sequence_idx,element,season_x,name,GW,team_x,value,minutes,last_1_goals_scored,last_1_assists,padding_used,position_encoded,actual,predicted,minutes_pred
13186,13186,348.0,2024-25,phil_foden,1.0,NaN,95.0,45.0,0.00,0.00,4,NaN,1.0,0.267196,0.228821
13187,13187,348.0,2024-25,phil_foden,2.0,NaN,95.0,0.0,0.00,0.00,3,NaN,0.0,0.000000,41.879860
13188,13188,348.0,2024-25,phil_foden,3.0,NaN,94.0,0.0,0.00,0.00,2,NaN,0.0,0.000000,1.692575
13189,13189,348.0,2024-25,phil_foden,4.0,NaN,93.0,0.0,0.00,0.00,1,NaN,0.0,0.000000,-0.178102
13190,13190,348.0,2024-25,phil_foden,5.0,NaN,93.0,20.0,0.00,0.00,0,NaN,1.0,0.097436,-0.189664
13191,13191,348.0,2024-25,phil_foden,6.0,NaN,93.0,24.0,0.00,0.00,0,NaN,1.0,0.708353,11.289324
13192,13192,348.0,2024-25,phil_foden,7.0,NaN,92.0,77.0,0.00,0.00,0,NaN,2.0,1.163957,48.427479
13193,13193,348.0,2024-25,phil_foden,8.0,NaN,92.0,24.0,0.00,0.00,0,NaN,4.0,1.666824,75.753014
13194,13194,348.0,2024-25,phil_foden,9.0,NaN,92.0,90.0,0.00,0.25,0,NaN,3.0,1.608748,71.203056
13195,13195,348.0,2024-25,phil_foden,10.0,NaN,93.0,90.0,0.00,0.00,0,NaN,2.0,1.905745,78.611160
13196,13196,348.0,2024-25,phil_foden,11.0,NaN,93.0,90.0,0.00,0.00,0,NaN,2.0,1.899232,78.816658
13197,13197,348.0,2024-25,phil_foden,12.0,NaN,92.0,90.0,0.00,0.00,0,NaN,2.0,2.009069,80.726990
13198,13198,348.0,2024-25,phil_foden,13.0,NaN,91.0,78.0,0.00,0.00,0,NaN,1.0,1.925001,79.717003
13199,13199,348.0,2024-25,phil_foden,14.0,NaN,91.0,0.0,0.00,0.00,0,NaN,0.0,0.000000,79.973351
13200,13200,348.0,2024-25,phil_foden,15.0,NaN,91.0,0.0,0.00,0.00,0,NaN,0.0,0.000000,4.726577
13201,13201,348.0,2024-25,phil_foden,16.0,NaN,91.0,90.0,0.00,0.00,0,NaN,2.0,0.405554,0.431883
13202,13202,348.0,2024-25,phil_foden,17.0,NaN,91.0,90.0,0.00,0.00,0,NaN,9.0,1.334664,61.027096
13203,13203,348.0,2024-25,phil_foden,18.0,NaN,91.0,90.0,0.25,0.00,0,NaN,2.0,1.825777,79.946251
13204,13204,348.0,2024-25,phil_foden,19.0,NaN,92.0,65.0,0.00,0.00,0,NaN,6.0,1.945080,82.366692
13205,13205,348.0,2024-25,phil_foden,20.0,NaN,92.0,90.0,0.00,0.25,0,NaN,8.0,1.978485,82.640152
13206,13206,348.0,2024-25,phil_foden,21.0,NaN,92.0,86.0,0.25,0.00,0,NaN,15.0,2.233968,84.495705
13207,13207,348.0,2024-25,phil_foden,22.0,NaN,92.0,62.0,0.50,0.00,0,NaN,19.0,2.381245,85.143456
13208,13208,348.0,2024-25,phil_foden,23.0,NaN,93.0,90.0,0.50,0.25,0,NaN,7.0,2.550045,86.262627
13209,13209,348.0,2024-25,phil_foden,24.0,NaN,93.0,71.0,0.25,0.00,0,NaN,2.0,2.523357,85.386864
13210,13210,348.0,2024-25,phil_foden,25.0,NaN,93.0,75.0,0.00,0.00,0,NaN,3.0,2.386636,80.992027
13211,13211,348.0,2024-25,phil_foden,26.0,NaN,93.0,90.0,0.00,0.00,0,NaN,2.0,2.433105,82.755135
13212,13212,348.0,2024-25,phil_foden,27.0,NaN,93.0,16.0,0.00,0.00,0,NaN,1.0,2.404167,82.762718
13213,13213,348.0,2024-25,phil_foden,28.0,NaN,92.0,68.0,0.00,0.00,0,NaN,3.0,1.087622,16.819288
13214,13214,348.0,2024-25,phil_foden,29.0,NaN,92.0,14.0,0.00,0.00,0,NaN,1.0,2.070100,79.206718
13215,13215,348.0,2024-25,phil_foden,30.0,NaN,92.0,0.0,0.00,0.00,0,NaN,0.0,0.000000,15.451546
13216,13216,348.0,2024-25,phil_foden,31.0,NaN,92.0,57.0,0.00,0.00,0,NaN,1.0,0.882301,3.970774
13217,13217,348.0,2024-25,phil_foden,32.0,NaN,92.0,0.0,0.00,0.00,0,NaN,0.0,0.000000,21.752335
13218,13218,348.0,2024-25,phil_foden,33.0,NaN,91.0,0.0,0.00,0.00,0,NaN,0.0,0.000000,3.148112
13219,13219,348.0,2024-25,phil_foden,34.0,NaN,91.0,0.0,0.00,0.00,0,NaN,0.0,0.000000,1.516141
13220,13220,348.0,2024-25,phil_foden,35.0,NaN,91.0,6.0,0.00,0.00,0,NaN,1.0,0.580816,1.165094
13221,13221,348.0,2024-25,phil_foden,36.0,NaN,91.0,75.0,0.00,0.00,0,NaN,3.0,0.701942,1.637473
13222,13222,348.0,2024-25,phil_foden,37.0,NaN,91.0,0.0,0.00,0.00,0,NaN,0.0,0.000000,45.036518
13223,13223,348.0,2024-25,phil_foden,38.0,NaN,91.0,8.0,0.00,0.00,0,NaN,1.0,0.901525,2.736123

In [22]:
print(torch.mean(y_test))
print(torch.var(y_test))

tensor(1.1469)
tensor(5.3394)

In [24]:
print(np.mean(points_predictions))
print(np.var(points_predictions))
print(np.max(points_predictions))

0.6529513
0.6448372
4.313949

In [25]:
print(np.mean(mins_predictions))
print(np.var(mins_predictions))
print(np.max(mins_predictions))

25.746609
1300.6908
89.24266

In [34]:
from sklearn.metrics import root_mean_squared_error, mean_absolute_error

rmse = root_mean_squared_error(y_test, points_predictions)
print(f"RMSE: {rmse}")

mae = mean_absolute_error(y_test, points_predictions)
print(f"MAE: {mae}")

RMSE: 2.059161424636841
MAE: 0.8934563398361206

In [35]:
X_test_numeric.shape

torch.Size([27283, 5, 16])

In [39]:
scores, total_score = season_performance_with_unlimited_transfers(
    y_test=y_test,
    predictions=points_predictions,
)

Players with NaN total_points_last_season: []
Number of NaN values remaining: 0
1.0 :  lukasz_fabianski
2.0 :  sepp_van_den_berg
3.0 :  tyler_dibling
4.0 :  daniel_jebbison
Bench players: ['lukasz_fabianski', 'sepp_van_den_berg', 'tyler_dibling', 'daniel_jebbison']
Bench cost: 170.0
Simulating season with unlimited transfers for 38 gameweeks
Available budget per gameweek: 830.0

--- Gameweek 1.0 ---
Players available for GW 1.0: 668
Welcome to the CBC MILP Solver
Version: 2.10.3
Build Date: Dec 15 2019

command line - /opt/anaconda3/envs/fpl_helper/lib/python3.11/site-packages/pulp/apis/../solverdir/cbc/osx/i64/cbc /var/folders/yv/683h12gj4mdc5txzm0lh6j0h0000gn/T/0fa97096062e45c8a50911ec7c12bb00-pulp.mps -max -timeMode elapsed -branch -printingOptions all -solution /var/folders/yv/683h12gj4mdc5txzm0lh6j0h0000gn/T/0fa97096062e45c8a50911ec7c12bb00-pulp.sol (default strategy 1)
At line 2 NAME          MODEL
At line 3 ROWS
At line 30 COLUMNS
At line 3687 RHS
At line 3713 BOUNDS
At line 4382 ENDATA
Problem MODEL has 25 rows, 668 columns and 2004 elements
Coin0008I MODEL read with 0 errors
Option for timeMode changed from cpu to elapsed
Continuous objective value is 2.56957 - 0.00 seconds
Cgl0003I 0 fixed, 10 tightened bounds, 0 strengthened rows, 0 substitutions
Cgl0003I 0 fixed, 1 tightened bounds, 0 strengthened rows, 0 substitutions
Cgl0004I processed model has 25 rows, 313 columns (313 integer (194 of which binary)) and 939 elements
Cbc0038I Initial state - 0 integers unsatisfied sum - 0
Cbc0038I Solution found of -2.56957
Cbc0038I Cleaned solution of -2.56957
Cbc0038I Before mini branch and bound, 313 integers at bound fixed and 0 continuous of which 2 were internal integer and 0 internal continuous
Cbc0038I Mini branch and bound did not improve solution (0.03 seconds)
Cbc0038I After 0.03 seconds - Feasibility pump exiting with objective of -2.56957 - took 0.00 seconds
Cbc0012I Integer solution of -2.5695714 found by feasibility pump after 0 iterations and 0 nodes (0.03 seconds)
Cbc0001I Search completed - best objective -2.5695713609457, took 0 iterations and 0 nodes (0.03 seconds)
Cbc0035I Maximum depth 0, 0 variables fixed on reduced cost
Cuts at root node changed objective from -2.56957 to -2.56957
Probing was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Gomory was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Knapsack was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Clique was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
MixedIntegerRounding2 was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
FlowCover was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
TwoMirCuts was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
ZeroHalf was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)

Result - Optimal solution found

Objective value:                2.56957136
Enumerated nodes:               0
Total iterations:               0
Time (CPU seconds):             0.01
Time (Wallclock seconds):       0.03

Option for printingOptions changed from normal to all
Total time (CPU seconds):       0.01   (Wallclock seconds):       0.04

                         name  actual  predicted
6118             levi_colwill     1.0   0.180068
6156    marc_cucurella_saseta     2.0   0.180068
6460               malo_gusto     1.0   0.180068
9842            ali_al_hamadi     1.0   0.287683
10146              liam_delap     2.0   0.287683
10716        christian_walton     2.0   0.163642
13452              rico_lewis     6.0   0.174683
20863          hwang_hee_chan     2.0   0.279990
21319  daniel_castelo_podence     1.0   0.279990
21433           pablo_sarabia     1.0   0.279990
26866           nico_gonzalez     3.0   0.275705
total_score for gameweek 1.0 : 23.0
GW 1.0 optimal team: ['ali_al_hamadi', 'christian_walton', 'daniel_castelo_podence', 'hwang_hee_chan', 'levi_colwill', 'liam_delap', 'malo_gusto', 'marc_cucurella_saseta', 'nico_gonzalez', 'pablo_sarabia', 'rico_lewis']
GW 1.0 score: 23.0
Team cost: 575.0

--- Gameweek 2.0 ---
Players available for GW 2.0: 675
Welcome to the CBC MILP Solver
Version: 2.10.3
Build Date: Dec 15 2019

command line - /opt/anaconda3/envs/fpl_helper/lib/python3.11/site-packages/pulp/apis/../solverdir/cbc/osx/i64/cbc /var/folders/yv/683h12gj4mdc5txzm0lh6j0h0000gn/T/af7110d22e464d9ca36d03a24f128553-pulp.mps -max -timeMode elapsed -branch -printingOptions all -solution /var/folders/yv/683h12gj4mdc5txzm0lh6j0h0000gn/T/af7110d22e464d9ca36d03a24f128553-pulp.sol (default strategy 1)
At line 2 NAME          MODEL
At line 3 ROWS
At line 30 COLUMNS
At line 3725 RHS
At line 3751 BOUNDS
At line 4427 ENDATA
Problem MODEL has 25 rows, 675 columns and 2025 elements
Coin0008I MODEL read with 0 errors
Option for timeMode changed from cpu to elapsed
Continuous objective value is 19.3794 - 0.00 seconds
Cgl0003I 0 fixed, 5 tightened bounds, 0 strengthened rows, 0 substitutions
Cgl0003I 0 fixed, 3 tightened bounds, 0 strengthened rows, 0 substitutions
Cgl0004I processed model has 25 rows, 485 columns (485 integer (410 of which binary)) and 1455 elements
Cbc0038I Initial state - 0 integers unsatisfied sum - 0
Cbc0038I Solution found of -19.3794
Cbc0038I Cleaned solution of -19.3794
Cbc0038I Before mini branch and bound, 485 integers at bound fixed and 0 continuous
Cbc0038I Mini branch and bound did not improve solution (0.01 seconds)
Cbc0038I After 0.01 seconds - Feasibility pump exiting with objective of -19.3794 - took 0.00 seconds
Cbc0012I Integer solution of -19.379368 found by feasibility pump after 0 iterations and 0 nodes (0.01 seconds)
Cbc0001I Search completed - best objective -19.379367828369, took 0 iterations and 0 nodes (0.01 seconds)
Cbc0035I Maximum depth 0, 0 variables fixed on reduced cost
Cuts at root node changed objective from -19.3794 to -19.3794
Probing was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Gomory was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Knapsack was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Clique was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
MixedIntegerRounding2 was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
FlowCover was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
TwoMirCuts was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
ZeroHalf was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)

Result - Optimal solution found

Objective value:                19.37936783
Enumerated nodes:               0
Total iterations:               0
Time (CPU seconds):             0.01
Time (Wallclock seconds):       0.01

Option for printingOptions changed from normal to all
Total time (CPU seconds):       0.01   (Wallclock seconds):       0.01

                                      name  actual  predicted
115                            kai_havertz     2.0   1.832307
609                            bukayo_saka     6.0   1.924640
5473                          joel_veltman     2.0   1.483171
5587                         danny_welbeck     9.0   1.829639
11781               trent_alexander_arnold     6.0   1.497725
12427                        mohamed_salah    10.0   1.945941
13415                        mateo_kovacic     1.0   1.915721
15277  joelinton_cassio_apolinario_de_lira     1.0   1.912063
15657                            nick_pope     3.0   2.049863
18774                          pedro_porro     6.0   1.509592
22536                    noussair_mazraoui     4.0   1.478707
total_score for gameweek 2.0 : 60.0
GW 2.0 optimal team: ['bukayo_saka', 'danny_welbeck', 'joel_veltman', 'joelinton_cassio_apolinario_de_lira', 'kai_havertz', 'mateo_kovacic', 'mohamed_salah', 'nick_pope', 'noussair_mazraoui', 'pedro_porro', 'trent_alexander_arnold']
GW 2.0 score: 60.0
Team cost: 740.0

--- Gameweek 3.0 ---
Players available for GW 3.0: 686
Welcome to the CBC MILP Solver
Version: 2.10.3
Build Date: Dec 15 2019

command line - /opt/anaconda3/envs/fpl_helper/lib/python3.11/site-packages/pulp/apis/../solverdir/cbc/osx/i64/cbc /var/folders/yv/683h12gj4mdc5txzm0lh6j0h0000gn/T/69e179d7aed84dc3a78127f9f601d4a6-pulp.mps -max -timeMode elapsed -branch -printingOptions all -solution /var/folders/yv/683h12gj4mdc5txzm0lh6j0h0000gn/T/69e179d7aed84dc3a78127f9f601d4a6-pulp.sol (default strategy 1)
At line 2 NAME          MODEL
At line 3 ROWS
At line 30 COLUMNS
At line 3773 RHS
At line 3799 BOUNDS
At line 4486 ENDATA
Problem MODEL has 25 rows, 686 columns and 2058 elements
Coin0008I MODEL read with 0 errors
Option for timeMode changed from cpu to elapsed
Continuous objective value is 20.9273 - 0.00 seconds
Cgl0003I 0 fixed, 7 tightened bounds, 0 strengthened rows, 0 substitutions
Cgl0003I 0 fixed, 4 tightened bounds, 0 strengthened rows, 0 substitutions
Cgl0004I processed model has 25 rows, 478 columns (478 integer (397 of which binary)) and 1434 elements
Cbc0038I Initial state - 2 integers unsatisfied sum - 0.888889
Cbc0038I Solution found of -20.9248
Cbc0038I Cleaned solution of -20.9248
Cbc0038I Before mini branch and bound, 476 integers at bound fixed and 0 continuous
Cbc0038I Full problem 25 rows 478 columns, reduced to 0 rows 0 columns
Cbc0038I Mini branch and bound did not improve solution (0.01 seconds)
Cbc0038I Round again with cutoff of -20.925
Cbc0038I Reduced cost fixing fixed 471 variables on major pass 2
Cbc0038I Pass   1: suminf.    0.09207 (2) obj. -20.925 iterations 2
Cbc0038I Pass   2: suminf.    0.88889 (2) obj. -20.9273 iterations 3
Cbc0038I Pass   3: suminf.    0.88889 (2) obj. -20.9273 iterations 0
Cbc0038I Pass   4: suminf.    0.09207 (2) obj. -20.925 iterations 3
Cbc0038I Pass   5: suminf.    0.88889 (2) obj. -20.9273 iterations 3
Cbc0038I Pass   6: suminf.    0.88889 (2) obj. -20.9273 iterations 1
Cbc0038I Pass   7: suminf.    0.88889 (2) obj. -20.9273 iterations 0
Cbc0038I Pass   8: suminf.    0.09207 (2) obj. -20.925 iterations 1
Cbc0038I Pass   9: suminf.    0.09207 (2) obj. -20.925 iterations 1
Cbc0038I Pass  10: suminf.    0.88889 (2) obj. -20.9273 iterations 2
Cbc0038I Pass  11: suminf.    0.44444 (2) obj. -20.9257 iterations 1
Cbc0038I Pass  12: suminf.    0.19061 (2) obj. -20.925 iterations 2
Cbc0038I Pass  13: suminf.    0.44444 (2) obj. -20.9257 iterations 2
Cbc0038I Pass  14: suminf.    0.19061 (2) obj. -20.925 iterations 1
Cbc0038I Pass  15: suminf.    0.09207 (2) obj. -20.925 iterations 3
Cbc0038I Pass  16: suminf.    0.09207 (2) obj. -20.925 iterations 1
Cbc0038I Pass  17: suminf.    0.09207 (2) obj. -20.925 iterations 1
Cbc0038I Pass  18: suminf.    0.09207 (2) obj. -20.925 iterations 0
Cbc0038I Pass  19: suminf.    0.09207 (2) obj. -20.925 iterations 0
Cbc0038I Pass  20: suminf.    0.09207 (2) obj. -20.925 iterations 0
Cbc0038I Pass  21: suminf.    0.09207 (2) obj. -20.925 iterations 0
Cbc0038I Pass  22: suminf.    0.19061 (2) obj. -20.925 iterations 1
Cbc0038I Pass  23: suminf.    0.44444 (2) obj. -20.9257 iterations 2
Cbc0038I Pass  24: suminf.    0.44444 (2) obj. -20.9257 iterations 0
Cbc0038I Pass  25: suminf.    0.19061 (2) obj. -20.925 iterations 2
Cbc0038I Pass  26: suminf.    0.09207 (2) obj. -20.925 iterations 1
Cbc0038I Pass  27: suminf.    0.09207 (2) obj. -20.925 iterations 0
Cbc0038I Pass  28: suminf.    0.88889 (2) obj. -20.9273 iterations 2
Cbc0038I Pass  29: suminf.    0.19061 (2) obj. -20.925 iterations 3
Cbc0038I Pass  30: suminf.    0.44444 (2) obj. -20.9257 iterations 1
Cbc0038I No solution found this major pass
Cbc0038I Before mini branch and bound, 474 integers at bound fixed and 0 continuous
Cbc0038I Full problem 25 rows 478 columns, reduced to 0 rows 0 columns
Cbc0038I Mini branch and bound did not improve solution (0.02 seconds)
Cbc0038I After 0.02 seconds - Feasibility pump exiting with objective of -20.9248 - took 0.01 seconds
Cbc0012I Integer solution of -20.924753 found by feasibility pump after 0 iterations and 0 nodes (0.02 seconds)
Cbc0006I The LP relaxation is infeasible or too expensive
Cbc0013I At root node, 0 cuts changed objective from -20.927265 to -20.927265 in 1 passes
Cbc0014I Cut generator 0 (Probing) - 1 row cuts average 5.0 elements, 1 column cuts (1 active)  in 0.000 seconds - new frequency is 1
Cbc0014I Cut generator 1 (Gomory) - 0 row cuts average 0.0 elements, 0 column cuts (0 active)  in 0.000 seconds - new frequency is -100
Cbc0014I Cut generator 2 (Knapsack) - 0 row cuts average 0.0 elements, 0 column cuts (0 active)  in 0.000 seconds - new frequency is -100
Cbc0014I Cut generator 3 (Clique) - 0 row cuts average 0.0 elements, 0 column cuts (0 active)  in 0.000 seconds - new frequency is -100
Cbc0014I Cut generator 4 (MixedIntegerRounding2) - 0 row cuts average 0.0 elements, 0 column cuts (0 active)  in 0.000 seconds - new frequency is -100
Cbc0014I Cut generator 5 (FlowCover) - 0 row cuts average 0.0 elements, 0 column cuts (0 active)  in 0.000 seconds - new frequency is -100
Cbc0014I Cut generator 6 (TwoMirCuts) - 0 row cuts average 0.0 elements, 0 column cuts (0 active)  in 0.000 seconds - new frequency is -100
Cbc0014I Cut generator 7 (ZeroHalf) - 0 row cuts average 0.0 elements, 0 column cuts (0 active)  in 0.000 seconds - new frequency is -100
Cbc0001I Search completed - best objective -20.924752712251, took 0 iterations and 0 nodes (0.02 seconds)
Cbc0035I Maximum depth 0, 390 variables fixed on reduced cost
Cuts at root node changed objective from -20.9273 to -20.9273
Probing was tried 1 times and created 2 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Gomory was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Knapsack was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Clique was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
MixedIntegerRounding2 was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
FlowCover was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
TwoMirCuts was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
ZeroHalf was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)

Result - Optimal solution found

Objective value:                20.92475271
Enumerated nodes:               0
Total iterations:               0
Time (CPU seconds):             0.02
Time (Wallclock seconds):       0.02

Option for printingOptions changed from normal to all
Total time (CPU seconds):       0.02   (Wallclock seconds):       0.02

                    name  actual  predicted
534    david_raya_martin     2.0   2.223672
724        thomas_partey     1.0   2.032606
5588       danny_welbeck     2.0   1.974437
9654    antonee_robinson     4.0   1.605670
12390          luis_diaz    15.0   2.084198
12428      mohamed_salah    17.0   2.097125
12694   andrew_robertson     6.0   1.619996
13302     erling_haaland    17.0   1.974085
18889    cristian_romero     1.0   1.629678
19079      son_heung_min     3.0   2.055141
19877         max_kilman     0.0   1.628144
total_score for gameweek 3.0 : 85.0
GW 3.0 optimal team: ['andrew_robertson', 'antonee_robinson', 'cristian_romero', 'danny_welbeck', 'david_raya_martin', 'erling_haaland', 'luis_diaz', 'max_kilman', 'mohamed_salah', 'son_heung_min', 'thomas_partey']
GW 3.0 score: 85.0
Team cost: 810.0

--- Gameweek 4.0 ---
Players available for GW 4.0: 692
Welcome to the CBC MILP Solver
Version: 2.10.3
Build Date: Dec 15 2019

command line - /opt/anaconda3/envs/fpl_helper/lib/python3.11/site-packages/pulp/apis/../solverdir/cbc/osx/i64/cbc /var/folders/yv/683h12gj4mdc5txzm0lh6j0h0000gn/T/040a72c6c91d4b61b834d5c826253e31-pulp.mps -max -timeMode elapsed -branch -printingOptions all -solution /var/folders/yv/683h12gj4mdc5txzm0lh6j0h0000gn/T/040a72c6c91d4b61b834d5c826253e31-pulp.sol (default strategy 1)
At line 2 NAME          MODEL
At line 3 ROWS
At line 30 COLUMNS
At line 3806 RHS
At line 3832 BOUNDS
At line 4525 ENDATA
Problem MODEL has 25 rows, 692 columns and 2076 elements
Coin0008I MODEL read with 0 errors
Option for timeMode changed from cpu to elapsed
Continuous objective value is 20.8154 - 0.00 seconds
Cgl0003I 0 fixed, 4 tightened bounds, 0 strengthened rows, 0 substitutions
Cgl0004I processed model has 25 rows, 494 columns (494 integer (414 of which binary)) and 1482 elements
Cbc0038I Initial state - 2 integers unsatisfied sum - 0.285714
Cbc0038I Solution found of -20.8138
Cbc0038I Cleaned solution of -20.8138
Cbc0038I Before mini branch and bound, 492 integers at bound fixed and 0 continuous
Cbc0038I Full problem 25 rows 494 columns, reduced to 0 rows 0 columns
Cbc0038I Mini branch and bound did not improve solution (0.01 seconds)
Cbc0038I Round again with cutoff of -20.814
Cbc0038I Reduced cost fixing fixed 488 variables on major pass 2
Cbc0038I Pass   1: suminf.    0.03018 (2) obj. -20.814 iterations 1
Cbc0038I Pass   2: suminf.    0.28571 (2) obj. -20.8154 iterations 2
Cbc0038I Pass   3: suminf.    0.03018 (2) obj. -20.814 iterations 1
Cbc0038I Pass   4: suminf.    0.03018 (2) obj. -20.814 iterations 1
Cbc0038I Pass   5: suminf.    0.03018 (2) obj. -20.814 iterations 0
Cbc0038I Pass   6: suminf.    0.28571 (2) obj. -20.8154 iterations 2
Cbc0038I Pass   7: suminf.    0.03018 (2) obj. -20.814 iterations 2
Cbc0038I Pass   8: suminf.    0.28571 (2) obj. -20.8154 iterations 2
Cbc0038I Pass   9: suminf.    0.03018 (2) obj. -20.814 iterations 1
Cbc0038I Pass  10: suminf.    0.03018 (2) obj. -20.814 iterations 1
Cbc0038I Pass  11: suminf.    0.03018 (2) obj. -20.814 iterations 0
Cbc0038I Pass  12: suminf.    0.03018 (2) obj. -20.814 iterations 0
Cbc0038I Pass  13: suminf.    0.03018 (2) obj. -20.814 iterations 0
Cbc0038I Pass  14: suminf.    0.03018 (2) obj. -20.814 iterations 0
Cbc0038I Pass  15: suminf.    0.03018 (2) obj. -20.814 iterations 0
Cbc0038I Pass  16: suminf.    0.03018 (2) obj. -20.814 iterations 1
Cbc0038I Pass  17: suminf.    0.03018 (2) obj. -20.814 iterations 1
Cbc0038I Pass  18: suminf.    0.03018 (2) obj. -20.814 iterations 0
Cbc0038I Pass  19: suminf.    0.28571 (2) obj. -20.8154 iterations 2
Cbc0038I Pass  20: suminf.    0.03018 (2) obj. -20.814 iterations 1
Cbc0038I Pass  21: suminf.    0.28571 (2) obj. -20.8154 iterations 1
Cbc0038I Pass  22: suminf.    0.03018 (2) obj. -20.814 iterations 2
Cbc0038I Pass  23: suminf.    0.03018 (2) obj. -20.814 iterations 0
Cbc0038I Pass  24: suminf.    0.03018 (2) obj. -20.814 iterations 0
Cbc0038I Pass  25: suminf.    0.03018 (2) obj. -20.814 iterations 0
Cbc0038I Pass  26: suminf.    0.03018 (2) obj. -20.814 iterations 0
Cbc0038I Pass  27: suminf.    0.03018 (2) obj. -20.814 iterations 0
Cbc0038I Pass  28: suminf.    0.28571 (2) obj. -20.8154 iterations 2
Cbc0038I Pass  29: suminf.    0.03018 (2) obj. -20.814 iterations 2
Cbc0038I Pass  30: suminf.    0.28571 (2) obj. -20.8154 iterations 2
Cbc0038I No solution found this major pass
Cbc0038I Before mini branch and bound, 492 integers at bound fixed and 0 continuous
Cbc0038I Mini branch and bound did not improve solution (0.01 seconds)
Cbc0038I After 0.01 seconds - Feasibility pump exiting with objective of -20.8138 - took 0.01 seconds

In [40]:
total_score.item()

2298.0

In [41]:
scores

                                                 team  gw_score
0   [ali_al_hamadi, christian_walton, daniel_caste...      23.0
1   [bukayo_saka, danny_welbeck, joel_veltman, joe...      60.0
2   [andrew_robertson, antonee_robinson, cristian_...      85.0
3   [alisson_ramses_becker, antonee_robinson, brya...      44.0
4   [bukayo_saka, chris_wood, david_raya_martin, d...      73.0
5   [bryan_mbeumo, chris_wood, david_raya_martin, ...      40.0
6   [cole_palmer, cristian_romero, danny_welbeck, ...      38.0
7   [antonee_robinson, bryan_mbeumo, cole_palmer, ...      45.0
8   [cole_palmer, diogo_dalot_teixeira, dwight_mcn...      56.0
9   [bryan_mbeumo, chris_wood, cole_palmer, danny_...      59.0
10  [alex_iwobi, antonee_robinson, bryan_mbeumo, c...      55.0
11  [bruno_borges_fernandes, bryan_mbeumo, chris_w...      45.0
12  [antonee_robinson, ashley_young, bruno_borges_...      91.0
13  [alex_iwobi, andre_onana, bukayo_saka, cole_pa...      80.0
14  [alex_iwobi, andre_onana, antonee_robinson, as...      62.0
15  [andre_onana, bruno_borges_fernandes, bukayo_s...      48.0
16  [alexander_isak, antonee_robinson, bryan_mbeum...     102.0
17  [alexander_isak, antonee_robinson, bruno_borge...      69.0
18  [alexander_isak, anthony_gordon, antonee_robin...      88.0
19  [alexander_isak, anthony_gordon, antonee_robin...      83.0
20  [alexander_isak, anthony_gordon, antonee_robin...      67.0
21  [alexander_isak, anthony_gordon, antonee_robin...      54.0
22  [alexander_isak, anthony_gordon, antonee_robin...      56.0
23  [alexander_isak, anthony_gordon, antonee_robin...      84.0
24  [alexander_isak, antonee_robinson, bruno_borge...      52.0
25  [alexander_isak, bryan_mbeumo, chris_wood, col...      85.0
26  [alisson_ramses_becker, bruno_borges_fernandes...      58.0
27  [bruno_borges_fernandes, bryan_mbeumo, chris_w...      68.0
28  [bruno_borges_fernandes, bryan_mbeumo, chris_w...      66.0
29  [alexander_isak, bruno_borges_fernandes, bryan...      39.0
30  [alexander_isak, bruno_borges_fernandes, bryan...      30.0
31  [alexander_isak, antonee_robinson, bruno_borge...      55.0
32  [alexander_isak, bruno_borges_fernandes, bryan...      63.0
33  [alexander_isak, bryan_mbeumo, jarrod_bowen, j...      55.0
34  [alexander_isak, bryan_mbeumo, cole_palmer, ja...      63.0
35  [alexander_isak, bryan_mbeumo, cole_palmer, da...      52.0
36  [bryan_mbeumo, chris_wood, cole_palmer, daniel...      37.0
37  [bryan_mbeumo, chris_wood, cole_palmer, daniel...      68.0